### ISSUE TITLE
Naming The Tool

### ISSUE THREAD

**Issue by stephanievaskomsu** [MESH-Research/CCR#1023]
### Problem/Why
Currently both the tool and the process have the same name, which can be misleading and lead to confusion.  

### Goal/What
Determine and adopt a new name for the tool. It is important to be able to distinguish both the tool and the process from each other moving forward. 

### Solution/How
Dean Long and Shelby will collaborate on a new name and Stephanie has given them two weeks (7/19). 

### To Do / Acceptance Criteria

- [x] Remind Dean Long and Shelby B about naming weekly until end of sprint

### Review Checklist

- N/A

### Accessibility Checklist

- N/A

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1023?planning-poker) with ZenHub @gmeben @stephanievaskomsu @wreality

**Comment by sattler9** [comment]
This tool might be helpful: https://namelix.com/app/?keywords=

**Comment by sattler9** [comment]
spreadsheet of options: https://docs.google.com/spreadsheets/d/1fg8T44GitP1I-sXkBqCRosKhg4Z39hgOp8V25k_FohI/edit#gid=0
