### ISSUE TITLE
Changing Font and Font Size

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#1035]
### Problem/Why
There are buttons on the submission page purport to control the font size of the content text.  These buttons do not work.

### Goal/What
When clicking the button for increase size, the font-size should increase.  When clicking the button for decrease size, the font-size should decrease

### Solution/How
Implement javascript handlers on the buttons that adjust the font sizes/styles.

### To Do / Acceptance Criteria

- [ ] Buttons functions as expected
- [ ] Unit tests added as needed

### Review Checklist

- [x] Tests pass
- [x] Buttons are functional

### Accessibility Checklist

- [x] Aria tags or other accessible name is present on the buttons
- [x] Automated a11y testing passes.

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1035?planning-poker) with ZenHub @gmeben @Sruthin86 @wreality

**Comment by sattler9** [comment]
The developer will make a recommendation after investigating on an upper limit.
