### ISSUE TITLE
Refactor API for submissions' users

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#1043]
### Problem/Why
The submission users API can be updated to simplify the client side API interface

### Goal/What
Match the submission users API to the spec approved in #910

#### Update backend
- [x] submission.graphql: Remove users field on submission type
- [x] submission.graphql: Add reviewers, submitters, review_coordinators fields on submission type
- [x] model: Add scoped relationships to submissions model for reviewers, submitters, review_coordinators
#### Update client
- [x] Update submission query to use new fields
- [x] Update submission details to use graphql fields instead of computed properties
- [x] Add new fields to any mocked data for submission queries
 - [x] Remove users field from any mocked content.

### Review Checklist

- [x] Unit tests pass
- [x] Cypress tests pass (no changes should be needed to cypress tests)

### Accessibility Checklist
**should** not result in front end changes.

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1043?planning-poker) with ZenHub @gmeben @Sruthin86 @wreality
