### ISSUE TITLE
Add comment tables to database and extend graphql API

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#1045]
### Problem/Why
Comments are currently not represented in the database or API

### Goal/What
API fields exist for querying and mutating comments.

### Solution/How
Add database tables for inline and overall comments with appropriate relationships and fields.  Implement schema changes as outlined in #910.  Created_by fields should be updated [automatically](https://dev.to/hasanmn/automatically-update-createdby-and-updatedby-in-laravel-using-bootable-traits-28g9)

**NOTE**
mutations should leverage lighthouse nested queries rather than being a root level mutation as outlined in #910.  This gives the apollo cache an opportunity to update related records.

```
extend type Mutation {
   updateSubmission(submission: SubmissionInput @spread): Submission @update
}

input SubmissionInput {
  id: ID!
  inline_comments: UpdateInlineCommentsHasMany
  overall_comments: UpdateOverallCommentsHasMany
}

input UpdateInlineCommentsHasMany {
    create: [CreateInlineCommentInput!]
}

input UpdateOverallCommentsHasMany {
    create: [CreateOverallCommentInput!]
}
input CreateInlineCommentInput {
  content: String!
  reply_to: String
  style_criteria: [String!]
 }

input CreateOverallCommentInput {
  content: String!
  reply_to: String
}
```

### To Do / Acceptance Criteria

- [x]  Add migrations for inline_comments and overall_comments
- [x] Add models with appropriate relationships to existing models
- [x] Add seed data as appropriate
- [x]  Add schema fields and types
- [x] Add unit tests to verify validation and relationships

### Review Checklist

- [x] Unit tests pass

**Comment by sattler9** [comment]
Holistic comments, comments made on the overall piece that could possibly be published, will be dealt with separately.

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1045?planning-poker) with ZenHub @gmeben @Sruthin86 @wreality
