### ISSUE TITLE
Match Frontend and Backend Password Strength Results

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#105]
**Problem/Why**

The new-password-input component can return a valid password result while the backed returns PASSWORD_NOT_COMPLEX, resulting in UI/UX confusion.

---

**Goal/What**

Ideally, there should be parity btw the implementation of zxcvbn in the front end and backend.

---

**Solution/How**

This is likely an upstream package issue that we need to develop tests for / contribute to the upstream packages if we can solve them.

https://github.com/olssonm/laravel-zxcvbn/pull/17

---
### To Do / Acceptance Criteria
- [ ]  Identify the root cause of the discrepancy
- [ ]  Submit PR to relevant packages.

### Review Checklist
- [ ] Parity btw frontend and backend zxcvbn results.

**Comment by wreality** [comment]
I'm beginning to think this might not be solvable.

Doing some digging, I found a test string that doesn't match: "➡♥✔😎👍"
PHP Score: 1, JS Score: 3

Right out of the gate, both libraries get the length of the string: 
PHP Length: 5 JS Length: 9

PHP is using mb_strlen for the length so it's doing it right.

The problem is even the Chrome console gets it wrong on the JS side... which is fine, but it gets it wrong **differently**

`"➡♥✔😎👍".length` : 7

The correct part to fix seems to be the javascript:
`[..."➡♥✔😎👍"].length`: 5

So, I'd be willing to bet, the JS implementation's score on multibyte strings would vary along with node versions (hence why it doesn't match chrome's result)

The PHP library is still seeing updates, while the JS library has been static for some time.  Getting the upstream PHP library updated to match the JS library's results seems the only way to go, but you'd have to start by getting the PHP library to count multibyte strings **wrong**, which doesn't seem a simple thing... especially if the javascript implementation isn't deterministic.

I see a couple of options.  
1. I'm going to see if there's a better, more current library pair that we could replace this with.
2. We could disallow emoji in passwords... so far, the libraries seem to match with "regular" extended characters.  As we discovered the other day, chrome won't let you use the emoji keyboard for a password prompt anyhow.
3. We could create an endpoint on the backend that returns a password score.
4. Get rid of the live feedback and move to the backend returning details about the complexity failure to be displayed.

My opinions:
2, I'm not thrilled about, I don't like password forms that restrict characters.
3. Also not thrilled.  The feedback would be slower and involve server load.
4. I don't love the UX of using password complexity and making the user submit the form to see if they've got a complex enough password.  This feels like instant/near instant feedback would be a UX requirement.

I think complexity checking is the way to go for passwords.  Length doesn't tell you anything, requiring certain characters just provides the formula for a dictionary attack. I'll keep looking around.  In the meantime, @gmeben @Sruthin86 any wise words to think about ?

Also, apologize for the brain dump.  Its late.. I'm annoyed.

**Comment by gmeben** [comment]
I like options 1 and 3. 

Although your opinions appear to be enumerated incorrectly, I agree with them. 

The only thing I disagree with is the statement that password length doesn't mean anything. From what I understand, length is the property that most strongly affects the strength of a password. A 20-character password with low 'complexity' can almost always be guaranteed to be stronger than an 8-character password with high 'complexity'. In my opinion, services and sites on the web would do better to show the user the explicit length of their entered passwords as they're typed.

**Comment by wreality** [comment]
You are right about length. My point was that it alone doesn't tell you anything about a "good" password. A password of "aaaaaaaaaaaaaaaa" is a good password in terms of length but is a trivial dictionary attack.

**Comment by wreality** [comment]
I'm tempted to bump this back to icebox while looking for the right solution.  It's a bug but is an edge case currently.  I haven't found a good library that has JS and PHP versions.

**Comment by wreality** [comment]
I'll be proposing during the review that we mark this wontfix and close it (to keep the history of the research done).

There's just not a good way of solving this currently.  Given that it's an edge case that I don't think we'll see in the wild for a good long while I think we can deal with it when the edge case arises and perhaps there will be a better overall solution out there by then as well.

**Comment by sattler9** [comment]
Estimate lowered because it wasn't done. Effort was put into determining we can't fix it.
