### ISSUE TITLE
Setup email sending development environment

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#106]
Configure laravel for sending emails and add lando configs for MailHog

## Todo

- [x] Configure laravel: https://laravel.com/docs/8.x/mail
- [x] Add lando config for mailhog: https://docs.lando.dev/config/mailhog.html

**Comment by sattler9** [comment]
Bumping this from a 2 to an 8 because Brian ended up building a whole tool to manages the extra containers to be turned on and off because they are resource heavy.
