### ISSUE TITLE
Add API fields containing current user’s role to submission, publication types

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#1068]
### Problem/Why
Frontend code has no simple mechanism to determine the currently logged in user’s role on a publication or submission. 

### Goal/What
Enable frontend code to be written to show/hide certain UI elements depending on a user’s role on that submission or publication. 

### Solution 

Two fields should be added to publication and submission types:
- role: the user’s specifically assigned roles on the object 
- effective_role: the user’s effective role from a permissions stand point taking into consideration their role on parent elements  

Fields should return either graphql Enums or string roles (‘submitter’, ‘reviewer’, etc)

Effective role example: if a user is a publication admin or editor their _effective_ role on a publication’s submission would be review_coordinator since they can perform all actions a review coordinator can.  

If the user is not logged in or has no role on the entity field should return null. 

### To Do / Acceptance Criteria

- [x] Implement publicationRole method on user model. 
- [x] implement. effectivePublicationRole method on user model. 
- [x] Implement submissionRole method on user model. 
- [x] Implement effectiveSubmissionRole method on user model
- [x] Add virtual fields on publication model to fetch current user role and effective_role using Auth::user()
- [x] Add virtual fields on submission model to fetch current user role and effective_role using Auth::user()
- [x] Add fields to submission and publication graphql types
- [x] Extend submission tests to ensure entities return correct values for each field 
- [x] Extend publication tests to ensure entities return correct values for each field. 

### Review Checklist

- [ ] Tests pass
- [ ] API returns new fields when queried

**Comment by Sruthin86** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1068?planning-poker) with ZenHub @gmeben @wreality
