### ISSUE TITLE
Prepare for the meeting with the PPJ Editorial team

### ISSUE THREAD

**Issue by sattler9** [MESH-Research/CCR#108]
**Problem/Why**

The CCR team will be meeting with the PPJ editorial team with Dean Long on Feb. 1st at 11:30 am

---

**Goal/What**

Need to plan out an agenda of any questions we want to ask as well as share what we've accomplished since the last meeting.

---

**Solution/How**

CCR Team will meet to brainstorm and create an agenda. Kelly can send the agenda in advance of the meeting.

---
### To Do / Acceptance Criteria
- [x] Set up a meeting for the CCR team to plan agenda during the week of Jan. 25th
- [ ] Team members complete any tasks generated during that meeting

**Comment by gmeben** [comment]
**Editorial Meeting Rolling Notes**: https://docs.google.com/document/d/1rd81MjhbUH1B0czjI0BYxR0U04AOidJfsisbulJVj2Q

**Comment by sattler9** [comment]
[Powerpoint slide deck ](https://michiganstate-my.sharepoint.com/:p:/r/personal/adamsb_msu_edu/_layouts/15/guestaccess.aspx?e=dvmqvB&share=Edi4elVmM99EkcLEFGDoHvIB0GrES2hwUNrOc2PxiM5wGA)
