### ISSUE TITLE
Remove usage of vue/Apollo’s useResult method

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#1084]
### Problem/Why
useResult has been deprecated in the most recent version of VueApollo to be removed in the 4.0 release. Since we're using the 4.0-alpha once useResult is removed we'll be unable to upgrade until this is remediated. Best to jump on it early I suppose. 

This is also currently throwing a depreciation warning in the JavaScript console which is polluting test results. 

### Goal/What
Remove all references to useResult in the client codebase. There are approx 30 references to it currently. 

### Solution/How
As described in vue/apollo code base:

> Use `computed` instead. Before: `const items = useResult(result, [], data => data.someField.myItems)` After: `const items = computed(() => result.value?.someField.myItems ?? [])`
 
Note, care should be taken to refactor appropriately rather than blindly replacing with the suggested computed value. We use the automatic picking feature of useResult in some places which will require some inspection of the code to resolve. 

### To Do / Acceptance Criteria

- [x] replace all references to useResult

### Review Checklist

- [x] all tests continue to pass
- [x] useResult is no longer referenced.

**Comment by wreality** [comment]
Bug is perhaps an overstatement, but probably closest in terms of priority since we don’t know when 4.0 will be released.

**Comment by wreality** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1084?planning-poker) with ZenHub @gmeben @sattler9 @Sruthin86

**Comment by wreality** [comment]
Per the maintainer, useResult will indeed be removed in 4.0

**Comment by gmeben** [comment]
This did not get auto-closed because there was no closing keyword in the description of the merging commit.
