### ISSUE TITLE
Refactor publication roles to use individual fields

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#1096]
### Problem/Why
Publication roles and associated user should be refactored similarly to submission roles to simplify the API experience.

### Solution/How
Refactor the publications schema:
```
type Publication {
    id: ID!
    name: String!
    created_at: DateTime
    updated_at: DateTime
    submissions: [Submission]! @hasMany
    #Removed
    users: [User]! @belongsToMany
    #End Removed
    #Added
    admins: [User!]
    editors: [User!]
   #endAdded
    is_publicly_visible: Boolean
    style_criterias: [StyleCriteria!]! @hasMany(relation: "styleCriterias")
}

input UpdatePublicationInput {
    id: ID!
    name: String
    description: String
    #Added Fields
    admins: [//HasMany updater]
    editors: [//HasMany updater]
    #End Added Fields
    style_criterias: UpdateStyleCriteriaHasMany
        @rename(attribute: "styleCriterias")
}
```

#### Backend
- [x] Update relationships in publication model
- [x] Update graphql schema
- [x] Update factorys and seeders
- [x] Update phpunit tests
#### Frontend
- [x] Update graphql mutations and queries
- [x] Update jest tests

### Review Checklist
- [ ] Tests pass and appropriately cover new / updated functionality

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1096?planning-poker) with ZenHub @gmeben @Sruthin86 @wreality
