### ISSUE TITLE
Fix Namespace Discrepancy in Logout.php

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#1127]
### Problem/Why
The namespace in `Logout.php` uses incorrect case sensitivity, which results in warnings appearing in the command line. The whitespace in this file is also abnormal.

### Goal/What
Change the namespace from `Graphql` to `GraphQL`. Remove extra whitespace.

### Solution/How
Update code in `Logout.php`

### To Do / Acceptance Criteria

- [x] Update code

### Review Checklist

- [ ] All existing tests pass
- [ ] No warning related to Logout.php is produced in the command-line when performing a rebuild or running PHPUnit tests

**Comment by wreality** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1127?planning-poker) with ZenHub @gmeben @sattler9 @Sruthin86
