### ISSUE TITLE
Add validation to reply_to_id and parentId

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#1162]
### Problem/Why
At the graphQL layer, a comment reply can have a reply_to_id that is not in the chain of replies it could reference (or indeed does not need to actually reference an actual existing comment it).  For parent_id, the referenced id doesn't need to belong to an existing comment or a comment existing on the submission.

### Goal/What
The mutation should fail if invalid values are provided for reply_to_id or parent_id.

### Solution/How
Add validation rules to the mutations.  Also consider adding rules attached to the laravel model itself for ensuring that parent_id is a valid value rather than relying on the Lighthouse layer to do it alone.
Rules:
- if parent_id is null, reply_to_id must be null as well
- if parent_id is NOT null:
  - the referenced comment must exist
  - the referenced comment submission_id  must equal the submission_id of the new comment,
  - the referenced comment's parent_id field must be null
- if reply_to_id is NOT null:
  - the referenced comment must exist
  - the referenced comment submission_id must equal the submission_id of the new comment
  - the referenced comment must be in the set [parent_id, ..child comments of parent_id]

### To Do / Acceptance Criteria

- [x] Update updateSubmission.inline_comments and updateSubmission.overall_comments with validation rules.
- [x] Add tests to ensure invalid data fails.

### Review Checklist

- [ ]  New tests created appropriately cover the scope of work.

**Comment by wreality** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1162?planning-poker) with ZenHub @gmeben @sattler9 @Sruthin86

**Comment by gmeben** [comment]
1. "if parent_id is null, reply_to_id must be null as well" 
    - Do we also want to check the converse of this and assert that "if `reply_to_id` is null, then `parent_id` must be null as well"?
2. "the referenced comment must exist" 
    - This appears to be already enforced by the integrity constraint at the database layer. User role assignments to submissions also appear to rely on the same constraint. 
3. "if parent_id is NOT null, the referenced comment's parent_id field must be null" 
    - I've been trying to understand what this means and I have not managed to recognize why this is desirable. This also seems at odds with how commenting currently works. All parent comments have null for `parent_id` and `reply_to_id` but all replies have both of these fields populated.

**Comment by wreality** [comment]
1. Sure
2. If that's the case 👍
3.  This is in relation to a single layer of nesting.  If the parent_id field is not null, this comment is a reply, which means the comment it's referencing as its parent must be a parent_id null comment (it cannot also be a reply)
