### ISSUE TITLE
Fix Scrolling on Reply References from Replies

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#1199]
### Problem/Why
When clicking upon the reference links from inline replies, the automatic scrolling does not move the screen to the correct position.

### Goal/What
Fix automatic scrolling so that the correct position is moved to when a reply reference is clicked upon.

### Solution/How
This will require some investigation.  The watch for `activeComment` is finding the correct element, but the computed scrollTo (using offsetTop) seems to not be resulting in a correct scroll.  Since offsetTop returns a value relative to the first positioned parent, likely a positioned element somewhere in the parent chain is throwing things off.  This however, is complete conjecture based on a very quick investigation and the problem may live somewhere else entirely. :-)

### To Do / Acceptance Criteria

- [x] Fix scroll position

### Review Checklist

- [ ]  Issue is resolved

**Comment by wreality** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1199?planning-poker) with ZenHub @gmeben @sattler9

**Comment by sattler9** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1199?planning-poker) with ZenHub @stephanievaskomsu
