### ISSUE TITLE
Add updateUser GraqphQL mutation.

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#120]
**Problem/Why**
---

The GraphQL endpoint does not have the ability to update user fields.

**Goal/What**
---

An API user should be able to update their username, email address, name, and password while logged into their account.

**Solution/How**
---

Create GraphQL endpoints for updating the user's information.

### To Do / Acceptance Criteria
-   [x] New graphql endpoint for updating user

### Review Checklist
-   An API user can update their:
  - [ ] Username
  - [ ] Password
  - [ ] Email address
  - [ ] Name
-   [ ] Appropriate unit tests

**Comment by sattler9** [comment]
Fields are limited to the ones that currently exist in the database. Other fields would need to be added to the database and then access added. The other fields will be a future issue/ticket.

**Comment by Sruthin86** [comment]
**Work Completed**
* Updated the schema to include migrations to update a user
* Added a UserPolicy to check if the user has an ability to update the record.
* Added unit tests to check the aforementioned functionality.

**Comment by gmeben** [comment]
Once [PR 128](https://github.com/MESH-Research/CCR/pull/128) is merged, I believe the following pseudo-code example will resemble the logic that handles the policy for determining how users can update user details:

```php

/**
 * This assumes that the current user has already been checked to be authenticated
 * @return Boolean
 */
public function UserUpdatePolicy() {

    // If the user is trying to update the user details 
    // for another user, then check if they have permission

    if ($current_user !== $user_to_be_updated) {
        return $current_user->can(Permission::UPDATE_USER_FOR_OTHERS);
    }

    // Otherwise, the user is trying to update their own user details,
    // which all users are allowed to do

    return true;
}
```

**Comment by gmeben** [comment]
Another way of handling the user update policy would require a change to the way permissions are being implemented at the moment (`update_user_for_others` changed to `update_users`) and an additional permission (`update_users_in_own_publication`) to handle the exception for Publication Administrators.

```php
/**
 * This assumes that the current user has already been checked to be authenticated
 * 
 * @param $current_user User
 * @param $user_to_be_updated User
 * @return Boolean
 */
public function UserUpdatePolicy($current_user, $user_to_be_updated) {

    // If the current authenticated user is trying to update the user details 
    // for another user, then check if they have permission based on role.

    // Application Administrators can update the users of any publication
    if ($current_user !== $user_to_be_updated 
        && $current_user->can(Permission::UPDATE_USERS)
    ) {
        return true;
    }

    // Publication Administrators can only update users within their own publication
    if ($current_user !== $user_to_be_updated
        && $current_user->can(Permission::UPDATE_USERS_IN_OWN_PUBLICATION)
    ) {
        return true;
    }

    // All users can update their own user details
    return $current_user === $user_to_be_updated;
}
```

**Comment by gmeben** [comment]
Relevant documentation: https://laravel.com/docs/8.x/authorization

**Comment by wreality** [comment]
Changed estimate from 5->8 as the work was more involved than initially suspected.
