### ISSUE TITLE
Make the "Scroll to Top" Button Functional

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#1200]
### Problem/Why
The "Scroll to Top" button at the bottom of the inline comments drawer is nonfunctional.

### Goal/What
Make the "Scroll to Top" button functional so that the top of the inline comments drawer is scrolled to when when this button is clicked upon.

### Solution/How
Add a click handler for scrolling. Add the handler to the button. Write testing to ensure functionality works as expected. 

### To Do / Acceptance Criteria

- [x] Add functionality to button
- [x] Add necessary testing

### Review Checklist

- [ ] The top of the inline comments drawer is scrolled to when the button is clicked

### Accessibility Checklist

- [ ] The button should be able to be accessed with a keyboard
- [ ] The button should be announce-able for screen readers

**Comment by wreality** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1200?planning-poker) with ZenHub @gmeben @sattler9
