### ISSUE TITLE
Reviewer Invitation Functionality

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#1256]
### Problem/Why
While user interface updates are being implemented on the Submission Details page in issue #1399 to support the invitation of reviewers and review coordinators, these features are non-functional.

### Goal/What
Implement functionality that allows a review coordinator, editor, or administrator, to send an email inviting a user to be assigned as a reviewer or review coordinator of a submission.

### Solution/How
Create the email, the functionality to send the email, and functionality to accept the invitation. If the user does not already exist in the system, the user should be staged immediately. A unique, default username and password should be generated for this staged user. Add an attribute to the user model `staged` to track whether or not a user is staged. 

This component should only be interactive for review coordinators, editors, publication administrators, and application administrators. The email should include a descriptive message about the invitation and a link to accept the invitation. 

### To Do / Acceptance Criteria

- [x] Create template for invitation email
- [x] Add functionality to stage a created user
- [x] Add functionality to send an invitational email to a supplied email address
- [x] Add functionality that unstages a user once an invitation is accepted

### Review Checklist

- [ ] A user that does not exist in the application can be invited as a reviewer to a submission

### Accessibility Checklist

- [ ] The language in the email message uses [plain language](https://sheribyrnehaber.com/plain-language-essential-for-content-accessibility/)
- [ ] Usage of color passes at least AA WCAG contrast ratio
- [ ] Font sizes are at least 16px

**Comment by sattler9** [comment]
The text will be canned and not editable by a member of the publication for this ticket.

**Comment by gmeben** [comment]
We agreed as a team that this will be broken out into frontend and design focused issues and this will become the backend-only issue.
