### ISSUE TITLE
Complete createUser endpoint test suite

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#126]
**Problem/Why**

The createUser test suite does not include tests for validation criteria for the various fields.

---

**Goal/What**

The test suite should test that validation criteria are being applied as intended.

---

**Solution/How**

#### In `backend/tests/Feature/CreateUserMigrationTest.php`
- [x] Add test for password presence, not empty and complexity validation
- [x] Add test for username presence and not empty
- [x] Add test for add test for email present, not empty and valid.
- [x] Rename `backend/tests/Feature/CreateUserMigrationTest.php` -> `CreateUserMutationTest.php`

### Review Checklist

- [x] Test suite complete
- [x] Tests pass

**Comment by sattler9** [comment]
This ticket was actually work done in ticket #120, but hadn't been documented as needing to be done.
