### ISSUE TITLE
User password reset

### ISSUE THREAD

**Issue by Sruthin86** [MESH-Research/CCR#127]
**Problem/Why**

As a user I cannot reset my password.

---

**Goal/What**

A user should be able to successfully reset their password following a link generated by the system.

---

**Solution/How**

Create a Contract to reset password "Illuminate\Contracts\Auth\CanResetPassword" using `lando artisan make:contract CanResetPassword` 
Generate a reset token and update the db with the reset token.
Link to documentation : https://laravel.com/docs/8.x/passwords

---

### To Do / Acceptance Criteria

- [ ] Create a Contract to reset password
- [ ] Generate a reset token.

### Review Checklist

- [ ] Ability to successfully update a password.

### Accessibility Checklist

- [ ] Check the page for AXE plugin.

**Comment by wreality** [comment]
How is this different from #21?

**Comment by gmeben** [comment]
We confirmed as a team that this is a duplicate and will close shortly.
