### ISSUE TITLE
Notifications for Determining Fitness for Review

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#1275]
### Problem/Why
When a decision is made on a submission that determines its fitness for review, users are not notified of this decision. This can result in reviewers and review coordinators not being aware that a submission is ready for review, delaying the review process.

### Goal/What
Notify all submitters, reviewers, review coordinators, and editors associated with a submission upon a user accepting, rejecting, or requesting a resubmission on a newly submitted submission.

### Solution/How
Listen for changes to submission states. Create notifications and events for when a submission is accepted, rejected, or requested for a resubmission. Add the logic for handling the different messages for the different status changes in the notification class.

### To Do / Acceptance Criteria

- [x] Add listeners, notifications, and events
- [x] Add PHPUnit testing to check that correct recipients receive notifications upon status changes

### Review Checklist

- [ ] Notifications are sent to correct users upon updating a submission's status

### Accessibility Checklist

- [ ] Copy for notifications uses [plain language](https://sheribyrnehaber.com/plain-language-essential-for-content-accessibility/)

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1275?planning-poker) with ZenHub @gmeben @Sruthin86 @vilagshe @wreality

**Comment by sattler9** [comment]
a separate ticket will be drafted for the creation of the copy text that is associated with these functions.
