### ISSUE TITLE
Update Docs for Database Setup

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#1276]
### Problem/Why
The [docs site](https://ccr.meshresearch.dev) does not include instructions for migrating and seeding the database, which is required for being able to log in as one of the seeded users. This means that developers setting up an instance of the application for the first time may not realize that extra work must be done in order to access the parts of the application that require authentication.

### Goal/What
Update the docs to include instructions for running the migrations and seeding.

### Solution/How
Add the following commands to the docs and include descriptions on what they do:

* `lando artisan migrate:fresh`
* `lando artisan db:seed`
* `lando artisan migrate:fresh --seed`

### To Do / Acceptance Criteria

- [ ] Update documentation

### Review Checklist

- [ ] Instructions for setting up the database are included

### Accessibility Checklist

- [ ] Documentation uses plain language

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1276?planning-poker) with ZenHub @gmeben @vilagshe
