### ISSUE TITLE
Add cypress-axe testing framework 

### ISSUE THREAD

**Issue by Sruthin86** [MESH-Research/CCR#130]
**Problem/Why**

There are no automated tests for accessibility in the application.

---

**Goal/What**
Automated tests, that check for accessibility issues are run every time the a new feature is added to the application.

---

**Solution/How**
Use cypress-axe [https://www.npmjs.com/package/cypress-axe] plugin to implement automated tests in CCR

---

### To Do / Acceptance Criteria

- [x] Add cypress-axe testing framework to the application.
- [x] Accessibility tests for homepage exists.
- [x] Accessibility issues on homepage are fixed. 

### Review Checklist

- [x] Cypress-axe plugin exists in the application and automated tests are successfully run.
- [x] Homepages pages pass the accessibility tests.

**Comment by Sruthin86** [comment]
**Work completed:**

- Installed cypress-axe, axe-core plugin on the CCR app.
- Updated the tests to include accessibility checks.
- Fixed the accessibility errors on the home page.

**Work remaining**
 - Add accessibility tests for login and registration page.
 - Fix the accessibility errors reported by axe plugin on login and registration page.

**Comment by gmeben** [comment]
@Sruthin86 The first task on the To Do list was completed today, right?

**Comment by Sruthin86** [comment]
We decided to add accessibility tests for the login and registration pages. The GitHub action will not be added as a part of this ticket. The appropriate fixes to fix the issues on the login and register page will be done as a part of new ticket which needs to be created.
