### ISSUE TITLE
Update Style Guide: Colors and Typography

### ISSUE THREAD

**Issue by stephanievaskomsu** [MESH-Research/CCR#1306]
### Problem/Why
Currently we have not established consistent colors and fonts across the CCR application. 

### Goal/What
Select fonts and a color palette that adheres to accessibility needs. 

### Solution/How
We will check in with the PPJ editorial team to determine their preferences and then use these as a springboard to determine the colors and fonts for this application. 

### To Do / Acceptance Criteria

- [x] Brainstorm color palette colors
- [x] Reach out to Shelby for input on color palette options
- [x] Meet with Shelby (Wednesday@ 11)
- [x] Determine color palette colors
- [x] Determine color palette colors accessibility guide (foreground/background)
- [x] Choose serif and sans-serif font families: Atkinson Hyperlegible and Georgia (https://apastyle.apa.org/style-grammar-guidelines/paper-format/font)
- [x] Document color palette colors in our guide
- [x] Determine color palette colors accessibility guide (foreground/background) in our guide
- [x] Document font families in our guide
- [x] Implement color changes

### Review Checklist

- [x] Style guide is updated with fonts, colors, and accessibility guide
- [x] Colors are updated and used in accordance with accessibility guidelines

### Accessibility Checklist

- [x] Do colors in the color palette meet accessibility criteria? Colorblindness, etc?
- [ ] Do fonts meet accessibility criteria? Low-vision, screen-reader usability, etc?

**Comment by wreality** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1306?planning-poker) with ZenHub @gmeben @sattler9 @Sruthin86 @vilagshe

**Comment by wreality** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1306?planning-poker) with ZenHub @stephanievaskomsu

**Comment by vilagshe** [comment]
I like this color tool ([https://coolors.co/2f5496-2ea3f2-66bcf5-8ccdf8-ffffff](https://coolors.co/2f5496-2ea3f2-66bcf5-8ccdf8-ffffff)). It's freemium at $3 a month to use all the built in accessibility features, but you can still use most things like color blindness and I like how you can move colors around or easily select different shades.

**Comment by sattler9** [comment]
I agree that is a nice color tool! I gave a presentation last year on choosing colors. The summary slide had these tools on it:
[Colorzilla](https://www.colorzilla.com/) - enables color selection from a website that can be added to Firefox or Chrome
[Webaim’s contrast checker](https://webaim.org/resources/contrastchecker/) – allows you to test your font color against the background color
[Webaim’s Link Contrast Checker](https://webaim.org/resources/linkcontrastchecker/) – includes body text check
[Color Picker](https://imagecolorpicker.com/color-code/2596be) – simplest of the options
[Coolors.co](https://coolors.co/) – another fancier color picker
[ColorHexa](https://www.colorhexa.com/18453b) – the one our web designer uses

Just mentioning them in case they help at all, but I am not surprised if others have their favorite tools too.

**Comment by vilagshe** [comment]
Created a Miro board to start messing with color palettes and took note of what colors we currently have/where they are being used. https://miro.com/app/board/uXjVPemADcE=/

**Comment by gmeben** [comment]
This is a relevant tool: https://reasonable.work/colors/

**Comment by vilagshe** [comment]
Met with Shelby, decided on the Triadic palette colors, with one slight modification (swapped the brown for a similar shaded of grey): https://coolors.co/2f5496-2ea3f2-ccd3e0-032c73-77beed-537b3d-520bbd-525252-ad347c

**Comment by gmeben** [comment]
I'm not sure how to test that fonts meet accessibility needs for those with low-vision or who rely on screen readers. I checked the other criteria I could verify, though.

**Comment by stephanievaskomsu** [comment]
I think we've done our best here with the research behind the fonts we chose to use?
________________________________
