### ISSUE TITLE
Capture Reasons for Approval Desk Decision

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#1327]
### Problem/Why
Currently, when a user of sufficient authority to determine a submission's fitness for review (approval desk) approves, rejects, or requests a resubmission on an initially submitted submission, their reasoning for doing so is not captured and made known to the submitter(s). 

### Goal/What
Extend the submission status changing dialog to include a text area where the reasoning for a decision can be provided and included in the email notification that's sent out to those associated with the submission. 

### Solution/How
Update the Vue template of the submission status changing dialog with a text area section where a user can draft a custom message. Refactor the GraphQL schema to use a nested input for submission statuses that includes a custom message. Extend the backend with a new model that includes explanation data. Add a custom mutation for changing the status of a submission and capturing the custom message. Update the email notification template to include the captured custom message. 

### To Do / Acceptance Criteria

- [x] Update dialog to include text area
- [x] Update the GraphQL schema 
- [x] Extend backend with new model and mutation
- [x] Update email notification template
- [x] Update Cypress testing to include text area

### Review Checklist

- [ ] A custom message can be provided when changing the status of a submission
- [ ] The custom message is displayed on the submission details page
- [ ] The custom message is included within the submission status change email notification

### Accessibility Checklist

- [ ] Color contrast of new interface elements pass at least AA rating
- [ ] Copy uses [plain language](https://sheribyrnehaber.com/plain-language-essential-for-content-accessibility/)

**Comment by wreality** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1327?planning-poker) with ZenHub @gmeben @Sruthin86 @stephanievaskomsu @vilagshe

**Comment by gmeben** [comment]
During team time on Friday, it was determined that additional database/backend work will be necessary in order to properly solve the problem of broadly associating decision explanation data with submissions so that they're not only related to notifications for individual users.
