### ISSUE TITLE
Handle Submission when Accepted for Review

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#1328]
### Problem/Why

The interactive elements on the Submissions page and Submission Review page currently do not change when a submission is accepted for review. They show the same interactions that are available when the submission is initially submitted, which is an unideal user experience.

### Goal/What

An open review button should appear in place of the fitness for review interactions on the submission review page. Once the submission is opened for review, interactions need to appear to enable the reviewer/review coordinator to close the review. 

### Solution/How

Replace interactions for (accept, request resubmit, reject) with an button that enables the review/review coordinator to open the review.

After the review is opened, replace the open review button with a close review button.

### To Do / Acceptance Criteria

- [x]  Interactions to determine fitness for review are replaced with an open review button once a submission status is changed from initially submitted to awaiting review
- [x] Open review button is replaced with a close review button after the review is opened
- [x] Add Cypress testing to ensure interactions work as expected

### Review Checklist

- [x] An editor can open a submission for review
- [x] An editor can close a submission for review
- [x] An editor can view approval desk options (Accepted as Final, Reject, Request Resubmission)

### Accessibility Checklist

- [x] Open review button is keyboard accessible
- [x] All colors adhere to WCAG AA guidelines
- [x] The controls for opening, closing, and approval desk options are annouceable via screen reader

**Comment by vilagshe** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1328?planning-poker) with ZenHub @gmeben @Sruthin86 @wreality @sattler9

**Comment by sattler9** [comment]
Should there be a step, "Under Review" between "Open review" and "Close Review" ?

**Comment by vilagshe** [comment]
The status of the submission will change to under review once it has been accepted. So while the open button is visible, the status should say under review.

**Comment by gmeben** [comment]
@vilagshe Almost. The status becomes `Awaiting Review` when a submission has been accepted for review. It will become `Under Review` when review is opened for the submission. Source: https://miro.com/app/board/o9J_l654lxo=/?moveToWidget=3458764529058747011&cot=14

@sattler9 When a review is closed on a submission, the status of the submission can become any one of these depending upon the action that's taken (or not taken): Awaiting Decision, Accepted as Final, Resubmission Requested, Revision Requested, Rejected, Expired, Deleted, or Archived.

**Comment by vilagshe** [comment]
Sorry, I don't have the flow chart in front of me at the moment. Grant is correct.

**Comment by vilagshe** [comment]
Refined the ticket/issue description

**Comment by vilagshe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1328?planning-poker) with ZenHub @stephanievaskomsu
