### ISSUE TITLE
Handle Submission when Requested for Resubmission

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#1329]
### Problem/Why
The interactive elements on the Submissions page and Submission Review page currently do not change when a submission is Requested for Resubmission as they do for acceptances and rejections.

### Goal/What
After a submission is requested for resubmission, all available options for the submission on the Submissions page and the Review page should be removed. This includes the buttons and options in the dropdown menu.

### Solution/How
Update the Vue templates on the Submissions page and Review page so that none of the status changing options on the buttons and in the dropdowns.

### To Do / Acceptance Criteria

- [x] Update Submissions page
- [x] Update Review page
- [x] Add Cypress testing to ensure elements appear/disappear as expected

### Review Checklist

- [x] Buttons that change the status are not displayed for submissions requested for resubmission
- [x] Dropdown that changes the status are not displayed for submissions requested for resubmission
- [x] New and existing tests pass

### Accessibility Checklist

- [x] There are no new color contrast issues introduced

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1329?planning-poker) with Zenhub @gmeben @stephanievaskomsu @vilagshe @wreality @Sruthin86
