### ISSUE TITLE
Handle Submission when Rejected

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#1330]
### Problem/Why
Submission rejection workflow is not currently implemented in the CCR application.

### Goal/What
After a submission is rejected all available options for the submission on the details page and the review page are removed. This includes the buttons and the the dropdown menu.

### Solution/How
Use the submissions graphql query to determine if a submission is in a rejected state and update the UI to not include any of the status changing buttons and the dropdown on the submission details and review page.

### To Do / Acceptance Criteria

- [x] Update UI to not include button that change the status 
- [x]  Update UI to not include dropdown that change the status 
- [x] Cypress and Jest tests exist

### Review Checklist

- [ ] Buttons that change the status are not displayed for rejected submissions
- [ ] Dropdown that change the submission are not displayed for rejected submissions
- [ ] Cypress and Jest Tests are written

### Accessibility Checklist

- [ ] Cypress and Screen reader tests pass

**Comment by Sruthin86** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1330?planning-poker) with ZenHub @wreality @gmeben @vilagshe @sattler9

**Comment by Sruthin86** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1330?planning-poker) with ZenHub @stephanievaskomsu

**Comment by Sruthin86** [comment]
**Work completed**

- Added functionality that removes status buttons on submission review page
- Added functionality that removes status dropdown on submissions page
- Added functionality that enables admins to still view rejected submission
- Added functionality that adds a tooltip for disabled buttons

**Comment by Sruthin86** [comment]
Work completed
- Cypress tests for the submissions page

Work in progress
- Cypress tests for the submissions  review page
