### ISSUE TITLE
Improve Documentation for Windows Development (WSL)

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#1334]
### Problem/Why
When a new developer using Windows follows the documentation to set up the application locally, there is nothing in the "Development Environments" section to direct the developer to the documentation on WSL development. This can result in a developer not being able to fully set up their environment for development. 

### Goal/What
Improve the documentation site to better direct Windows developers to the documentation for using WSL. 

### Solution/How
Add content to the "Development Environments" section in the docs that directs developers using Windows  to the [WSL Developer Notes](https://ccr.meshresearch.dev/contributing/wsl.html#wsl-developer-notes) section. 

### To Do / Acceptance Criteria

- [x] Update documentation

### Review Checklist

- [ ] The documentation makes it clear that WSL is to be used for Windows developers

### Accessibility Checklist

- [ ] Copy uses [plain language](https://sheribyrnehaber.com/plain-language-essential-for-content-accessibility/)

**Comment by wreality** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1334?planning-poker) with ZenHub @gmeben @Sruthin86 @vilagshe @stephanievaskomsu
