### ISSUE TITLE
Update documentation site home page.

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#134]
**Problem/Why**

The documentation site home page (<https://ccr.meshresearch.dev/>) does not include a description of the project or list of important sponsors.

---

**Goal/What**

The documentation site should include a high-level overview of the project and its goals as well as a list of sponsors for the project with logos.

---

**Solution/How**

Update `docs/index.md` to include a high-level description of the project and its goals as well as a list of major sponsors of the project.

---

### To Do / Acceptance Criteria

- [x] Project description on docs index page
- [x] List of sponsors on index page.

**Comment by gmeben** [comment]
Here's the description I wrote on hcommons.org for CCR:

### Collaborative Community Review (CCR)

[CCR](https://github.com/MESH-Research/CCR) is an open source web tool representing the values and intent of [Formative Peer Review (FPR)](https://publicphilosophyjournal.org/about/review/) meant for handling reviews of multimedia (especially written) intended to be published by journals or publications. CCR will be used to satisfy the various needs of the peer review process for works in academic and public scholarship. It has been funded via grant by the Mellon Foundation. CCR will supplement the [Public Philosophy Journal (PPJ)](https://publicphilosophyjournal.org/) headed by Dean Christopher Long at MSU.

**Comment by sattler9** [comment]
Have PPJ's logo be listed as a sponsor

**Comment by wreality** [comment]
Link to preview docs: @sattler9 

https://deploy-preview-198--eloquent-galileo-3be94a.netlify.app/

**Comment by sattler9** [comment]
The green #3EAF7C is too light and doesn't pass a11y. I do like how the sponsors are laid out.
