### ISSUE TITLE
Update default mailfrom address in lando config

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#1354]
### Problem/Why
With the recent introduction of automatic notifications being sent upon submission status changes, there is a fatal error encountered while seeding when there is no "from" address specified in the backend config file.  The default lando setup leaves this value empty/null.

### Goal/What
Ensure the `MAIL_FROM_ADDRESS` is by default 'test@example.com'

### Solution/How
Update `backend.default.env` to specify the default value.  Current developers can either delete their `backend/.env` and run `lando rebuild -y` or edit `backend/.env` directly with the new value.

### To Do / Acceptance Criteria

- [x] Update default env

### Review Checklist

- [x] New lando installs use the default value.

**Comment by wreality** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1354?planning-poker) with ZenHub @gmeben @Sruthin86 @vilagshe
