### ISSUE TITLE
Design Interactions for Inviting a New Reviewer to the Application

### ISSUE THREAD

**Issue by vilagshe** [MESH-Research/CCR#1400]
### Problem/Why
Currently only users who have a registered account can be assigned as a reviewer to a submission. If an email address is not associated with an active user, a reviewer cannot be assigned for that email address. Also, the user interface on the submission details page does not include any components that allow a user to invite a user that does not belong in the system.

### Goal/What
Design how the interactions could look for inviting a new reviewer to the application from the Submission Details page.

### Solution/How

Complete mock ups or wireframes to envision how these interactions will take place.

### To Do / Acceptance Criteria

- [x] Complete several wireframes/mockups to invite a new reviewer to the application.

### Review Checklist

- [ ] Several different ways to invite a new reviewer to the application are captured.

### Accessibility Checklist

- [ ] Colors adhere to WCAG AA guidelines.

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1400?planning-poker) with Zenhub @gmeben @Sruthin86 @stephanievaskomsu @vilagshe @wreality

**Comment by vilagshe** [comment]
Invite a new reviewer as a form on the Submission Details page: https://xd.adobe.com/view/8400e822-79be-4b94-ab0c-04ceaf2ac90b-d153/

Invite a new reviewer as a popup dialog: https://xd.adobe.com/view/68840d99-a5f9-4ff4-af40-e81804366eed-3dd7/

Invite a new reviewer as a textinput on the Submission Details page: https://xd.adobe.com/view/e20f797b-2200-41af-be98-854d9f7d30a5-b75c/

**Comment by vilagshe** [comment]
Invite a new reviewer as a form (two buttons, one for new users, one for existing) with activity on bottom: https://xd.adobe.com/view/e7c0d1c6-def9-4d83-9f3b-dc5c02f02f53-b293/grid

**Comment by vilagshe** [comment]
Final Design: https://xd.adobe.com/view/5858cd91-9ced-4cb9-b21e-d5be283fce35-0d0b/
