### ISSUE TITLE
Implement client UI for updating user profile metadata

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#142]
**Problem/Why**

Users cannot enter profile data associated with their user account.

---

**Goal/What**

Users should be able to enter profile data associated with their user account.  See #64 for proposed profile metadata fields.

---

**Solution/How**

Add page inside of the `AccountLayout`  pages to allow the user to update metadata.

---

### To Do / Acceptance Criteria

- [x] Create new `UserProfile.vue` with form fields for user profile data based on #64
- [x] Validate data as appropriate / necessary 
- [x] Save the user profile metadata using the updateUser mutation (implementation described in #8)
- [x] Implement jest tests for any new interactive components
- [x] Implement cypress tests for functionality.

### Review Checklist

- [x] User profile metadata is saved.
- [x] Tests are complete and passing

### Accessibility Checklist

- [ ] All form fields have appropriate aria tags
    - Uncertain
- [x] Interactive page elements implement appropriate accessibility features.

**Comment by sattler9** [comment]
Still to do:

- about 2 pages of documentation to write on custom components
- need to write all the tests
- May be done this week

**Comment by sattler9** [comment]
Brian asked for help writing the cypress tests. Grant volunteered. Brian will write the Jest tests

**Comment by gmeben** [comment]
I completed the first Cypress tests.

**Comment by gmeben** [comment]
Some more remarkable behavior I noticed:

When you enter a keyword in the Interest Keyword input and press the Return key to add the term to the list, the screen reader announces, "[keyword] deleted." 

The screen reader is silent when tabbing through the saved interest keywords and when pressing the Return key to delete them. 

Focusing the Save button and pressing the Return key makes the screen reader announce, "Saving. Button disabled." Clicking on the Save button only makes the screen reader announce, "Saving."
