### ISSUE TITLE
Application Admin users should be able to view a list of all users in the system.

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#143]
**Problem/Why**

Application and Publication administrators users have no visibility into what users exist in the system.

---

**Goal/What**

A list of all users should be provided to an Application Admin-protected route.

---

**Solution/How**

Create UI page displaying a list of users.

---

### To Do / Acceptance Criteria

- [x] Create a new ViewUsers page under the Application Admin routes.
- [x] Retrieve a list of users from the GraphQL API and display them to the user.
- [x] Add unit tests for any new interactive components
- [x] Add integration tests 

### Review Checklist

- [x] Users list is displayed.
- [x] Users list is only visible to application admins

### Accessibility Checklist

- [x] Appropriate accessibility tags
- [ ] Information architecture tagged and appropriate for screen readers.

**Comment by Sruthin86** [comment]
Work completed:

-  Updated the frontend graphql schema to query for users in the system
- Updated the view to include pagination
- Updated the styles on the pages to make it more presentable

Work remaining:
- Implement frontend tests
- Check for accessibility issues.

**Comment by gmeben** [comment]
Adding a border to avatars as a solution to the one a11y is, unfortunately, not as trivial as I thought it would be. These elements have an `overflow: hidden` applied to them which makes it hard to get `box-shadow`s or `border`s applied to them.

Another solution involves nesting avatars within round Quasar button elements, but this means that all avatars must be displayed as circular, which feels limiting and doesn't look as good (in my opinion) within lists of avatars.

I'm still trying to figure out the best solution.

**Comment by Sruthin86** [comment]
Grant reviewed the functionality and code. Merged the functionality into development branch and ready to be moved.
