### ISSUE TITLE
Limit comment modification to comment authors only

### ISSUE THREAD

**Issue by vilagshe** [MESH-Research/CCR#1542]
### Problem/Why
Currently inline and overall comments can be modified by any user. 

### Goal/What
Enable comments to be modified only by the user that authored the comment. Other users should not be able to modify comment text for comments they did not author. 

### Solution/How
Add checks when a user clicks on "Modify Comment" to ensure that user is the comment author before allowing the comment modification mutation to execute. Disable the modification option for non-authors and provide a tooltip.

### To Do / Acceptance Criteria
* [x] Add checks on the comment components
* [x] Add checks in the backend to ensure only the author of a comment can modify that comment
* [x] Add Cypress tests

### Review Checklist
* [x] Comments can be modified by their author
* [x] Comments cannot be modified by other users
* [x] The "modify comment" menu option is not available for non-authors

### Accessibility Checklist
* [x] Cypress testing passes

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1542?planning-poker) with Zenhub @gmeben @vilagshe @wreality
