### ISSUE TITLE
Publications should have a setting to disable/enable new submissions 

### ISSUE THREAD

**Issue by Sruthin86** [MESH-Research/CCR#1578]
### Problem/Why
Currently there is no setting to toggle disable submissions to a publication by publication admins. 

### Goal/What
Prepare for toggling disabling  submissions to a publication.

### Solution/How
This can be achieved by adding a db column to the Publications table that will indicate if a publication can accept submissions and extending the Submission Policy to reject submissions to the publications that have submissions disabled.

### To Do / Acceptance Criteria

- [x] Add a db column `is_accepting_submissions` to the Publications table that indicates if a publication can accept submissions
- [x] Extend the Submission Policy for submission creations to check the Publication setting
- [x] Add PHPUnit testing to verify that the new db column value can be toggled
- [x] Add PHPUnit tests to verify that submissions cannot be made to a publication that has submissions disabled

### Review Checklist

- [x]  A db column exists in the Publications table that indicates wether a publication can accept submissions.
- [x]  A  Submission Policy exists  that checks the Publications table and determines if the publication can accept a submission.
- [x] PHP Unit tests exists.

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1578?planning-poker) with Zenhub @gmeben @vilagshe @wreality
