### ISSUE TITLE
Invitation Email Validation

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#1580]
### Problem/Why
When entering an invalid email address into the user search input of a user invitation form and submitting, an error message popup rightfully appears. However, the message is generic and the user is still invited to the submission, which is visible upon refreshing the page.

### Goal/What
Prevent invitations for users that don't have valid email addresses on the frontend and backend. Provide an appropriate message in the error popup that appears.

### Solution/How
Add code to validate the email address on the backend. Add code to return a bespoke error message in the response when the supplied email is invalid. Change the code so that this validation prevents a user from being added to the submission. Add code on the frontend to correctly handle and display the error response. 

### To Do / Acceptance Criteria

- [x] Add email validation logic to the backend that prevents invalid email inputs
- [x] Add error response handling to the frontend
- [x] Add PHPUnit testing to ensure response works as intended
- [x] Add Cypress testing to ensure user experience works as intended

### Review Checklist

- [ ] Using the email address "invalidemail" results in an appropriate error message
- [ ] Using the email address "invalidemail" results in no user being added to the submission after refreshing the page

### Accessibility Checklist

- [ ] The error message uses plain language

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1580?planning-poker) with Zenhub @gmeben @Sruthin86 @vilagshe @wreality
