### ISSUE TITLE
Notify Users Upon Invitation Acceptance

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#1582]
### Problem/Why
When a user accepts an invitation to a submission as a reviewer or review coordinator, no one is notified. The only indication of the status of their assignment is from the "unconfirmed" icon appearing beside a user that appears within the Reviewers or Review Coordinator sections, but there is no event that's dispatched at the moment of the invitation acceptance. 

### Goal/What
Notify other users associated with the submission that a user has accepted an invitation to the submission. 

### Solution/How
Create a new notification for invitation acceptances and dispatch this upon setting a value of the `accepted_at` property of `SubmissionInvitation` models. Include the user's name/username and the invited role in the notification. The notification should be in-app and by email. 

### To Do / Acceptance Criteria

- [x] Create email notification
- [x] Create in-app notification
- [x] Add code to dispatch notification upon submission invitation acceptances

### Review Checklist

- [ ] A submitter is notified upon an invited reviewer accepting the invitation
- [ ] A submitter is notified upon an invited review coordinator accepting the invitation
- [ ] A reviewer is notified upon an invited reviewer accepting the invitation
- [ ] A reviewer is notified upon an invited review coordinator accepting the invitation
- [ ] A reviewe coordinator is notified upon an invited reviewer accepting the invitation
- [ ] A reviewe coordinator is notified upon an invited review coordinator accepting the invitation

### Accessibility Checklist

- [ ] Language used in the notification uses [plain language](https://sheribyrnehaber.com/plain-language-essential-for-content-accessibility/)

**Comment by sattler9** [comment]
Stephanie volunteered to write the copy for the email.

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1582?planning-poker) with Zenhub @gmeben @Sruthin86 @vilagshe @wreality

**Comment by sattler9** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1582?planning-poker) with Zenhub @stephanievaskomsu
