### ISSUE TITLE
Fix Color Contrast of Unread Notifications

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#1587]
### Problem/Why
As of the color scheme update, the background and foreground colors of unread notifications within the in-app notification dropdown no longer pass WCAG AA color contrast. 

![Screenshot of 2 unread in-app notifications beside 1 read notification](https://images.zenhubusercontent.com/5ff7670b9384a948b4663b2d/07b5e5e5-fc35-4aa8-a52d-228b8a660964)

https://webaim.org/resources/contrastchecker/?fcolor=757575&bcolor=77BEED

### Goal/What
Change the background color so that it passes WCAG AA color contrast.

### Solution/How
Update the designated background color for unread notification items. Consider changing the color to the previous light blue color

### To Do / Acceptance Criteria

- [x] Change background color

### Review Checklist

- [x] Unread notifications pass WCAG AA color contrast

### Accessibility Checklist

- [x] No other color contrast issues are introduced

**Comment by wreality** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1587?planning-poker) with Zenhub @gmeben @vilagshe
