### ISSUE TITLE
fix: Lint/Style Checking on 0.9.0 CHANGELOG

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#161]
### Problem/Why
A markdown linting failure occurred with the release of the CHANGELOG for release 0.9.0: https://github.com/MESH-Research/CCR/runs/2027621976

### Goal/What
CHANGELOG.md should not have linting errors and automated tools should generate files that pass linting.

### Solution/How
Fix the listed errors in a new branch and update build tools to generate well-formatted files.

### To Do / Acceptance Criteria

- [x] Fix errors
- [x] Update build tools.
- [x] Update docs re: how to create a release

### Review Checklist

- [x] Linting errors should no longer be present

**Comment by wreality** [comment]
I noticed this last night, but hadn't figured out how to deal with it yet. The change log is autogenerated and I don't want to have to manually fix it every time. 

It's also the same changelog format that a wide number of packages use now so I'm curious as to why it generates a lint erroring changelog. 

I'm investigating options.

**Comment by wreality** [comment]
N.b. This doesn't require a release since the changes don't impact the application.

**Comment by gmeben** [comment]
@wreality Do we not consider the application's documentation as part of the application? It lives in the same repository.
