### ISSUE TITLE
Update app header and favicon with new logos

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#1659]
### Problem/Why
The name of the application has changed and the header of the application doesn't reflect its new name.

### Goal/What
Update the header to match the new application  name and add the logo to the header.  Additionally the favicon is still the quasar default.

### Solution/How
Update the header component with the images (to come shortly and be attached to this issue by @wreality). Also update the favicon with the favicon image (also to come)

### To Do / Acceptance Criteria

- [ ] Update header
- [ ] Update favicon

### Review Checklist

- [ ] Both are updated

### Accessibility Checklist

- [ ] Adjustments may be needed to colors for header usage.

**Comment by wreality** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1659?planning-poker) with Zenhub @gmeben @sattler9 @Sruthin86 @vilagshe

**Comment by wreality** [comment]
![Pilcrowfavicon.png](https://images.zenhubusercontent.com/5fe17935da86cae135bcd2ab/4c61566c-902e-4e49-91ab-3179db3719c1)![PilcrowLogo.png](https://images.zenhubusercontent.com/5fe17935da86cae135bcd2ab/e04da807-6ad4-4934-8e03-e6e293012abf)

**Comment by gmeben** [comment]
This appears to be replacing issue #172, so that will be closed.
