### ISSUE TITLE
Application Admins should be able to view user details

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#174]
### Problem/Why
Application admins can view the list of all users in the system but cannot view more details on each user.

### Goal/What
Application Admins should be able to view details on each user in the system.

### Solution/How
Implement a user details page that displays the details of each user listed on the admin/users index page. 

Use Quasar components and styling to achieve different layouts under different breakpoints (large, medium, small, extra small) according to the prototypes from Issue #196.

### To Do / Acceptance Criteria

- [x] Add a route and page for `admin/users/{id}`
- [x] Implement user fetching from backend
- [x] Display basic user information (username, name, email)
- [x] Adjust page layout based on breakpoints (large, medium, small, extra small)

### Review Checklist

- [ ] Application Admins can view details of each user

### Accessibility Checklist

- [ ] Accessibility check pass

**Comment by Sruthin86** [comment]
Link to the wireframes: https://xd.adobe.com/view/4f17b02d-21d3-42b1-9f5e-fe8262316b1c-1a44/

**Comment by Sruthin86** [comment]
Work completed:

- Implemented user details and tabs for roles on the desktop size 
- Added the correct icons for the user metadata

Work remaining:
- Needs mobile and tablet layout updates.
- Needs conditions to show appropriate data when metadata is not present.

**Comment by gmeben** [comment]
Sections, Icon Set 2 - https://xd.adobe.com/view/398d5b99-9239-485c-ad9f-ff3ed5d42dfc-6cde/

**Comment by gmeben** [comment]
I made progress on this enough to consider it acceptably done according to the criteria. The user details page shows the name, username, email, and (now) role of users. Here's some things to note:

* The listed user items on the All Users page now link to the user details pages.
* I've decided to implement the simpler [section based layout from my designs in XD](https://xd.adobe.com/view/398d5b99-9239-485c-ad9f-ff3ed5d42dfc-6cde/) as my previous accessibility testing of the default QTabs component revealed that this violated the a11y specifications of axe-core 4.2 I have not yet tested QTabs with the recent release of 4.2.1 so this might've changed.
* The relationship that users have to publications and submissions does not yet consider role, so roles can't yet express the publication they're associated with in the roles section.
* Trying to achieve the precise layout that I designed in XD might not be feasible using Quasar. It appears the default flex-based layout has limitations with changing the alignment of elements between different breakpoints. I've asked [a question pertaining to this here](https://github.com/quasarframework/quasar/discussions/9395) so hopefully we get some expert input soon.

**Comment by gmeben** [comment]
I've got the integration test passing but the unit test has a problem with what I suspect is the usage of the `$route` property at `user_id: this.$route.params.id` on line 140 of UserDetails.vue. I encounter these errors:

`[Vue warn]: Error in data(): "TypeError: Cannot read property 'params' of undefined"`

`[Vue warn]: Error in render: "TypeError: Cannot read property 'username' of undefined"`

**Comment by gmeben** [comment]
I verified @wreality's fix to the unit test works locally.

@Sruthin86 Are you still interested in reviewing this?
