### ISSUE TITLE
Implement fuzzy searching for users api

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#175]
### Problem/Why
As the user list grows, an application admin should be able to search for a user in the list.

### Goal/What
The application admin should be able to filter the users list via a fuzzy search for email, name, and username.

### Solution/How
Update the GraphQL endpoint to allow a search parameter to be added which implements filtering users.  For inspiration: https://dev.to/khalyomede/create-an-easy-fuzzy-loose-search-with-laravel-5-34a4  

### To Do / Acceptance Criteria

- [x] Update the users list endpoint to accept a search parameter
- [x] Implement fuzzy search logic on username, name, and email

### Review Checklist

- [ ] API returns filtered user results

**Comment by gmeben** [comment]
I came across `@search` on the Lighthouse documentation for directives and it looks like it could fulfill the needs of this work: https://lighthouse-php.com/5.3/api-reference/directives.html#scope

It uses Laravel Scout, which is already installed in our stack.

**Comment by gmeben** [comment]
Apparently, Laravel Scout uses Algolia by default, which requires private ID and secret credentials provided by Alogila to be stored in the Scout configuration file: https://laravel.com/docs/master/scout#algolia

I don't believe we want to have this kind of dependency so I'm looking at alternative drivers. I'm looking at this one in particular: https://github.com/teamtnt/laravel-scout-tntsearch-driver
