### ISSUE TITLE
Determine best practice for reusing form/validation logic throughout application 

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#181]
### Problem/Why
Currently, the account edit page and the the account create page duplicate validation logic. This goes against DRY practices and makes the code more difficult to maintain. 

### Goal/What
Forms that share common fields should be able to reuse validation (and potentially store/retrieval) logic in an organized and maintainable way. 

### Solution/How

Research current best practices and determine the best way to architect our components and validation to be flexible and reusable. Use existing packages where appropriate. 

### To Do / Acceptance Criteria

- [x] Present to team a proposal for implementing the solution.

**Comment by wreality** [comment]
Here's the basics of what I've come up with based on my research.  

We currently use vulidate, which is a model-based validation plugin.  The other option is primarily vee-validate, which uses template-based validation.   Our model-based approach with vulidate seems to be the better approach for us, based primarily on what we're used to in our server side frameworks.  

The struggle becomes finding a way to encapsulate validation rules for a field so when that field is included in another template, the validation logic can be pulled in as well.  Mixins provide a good way to handle validation method reuse, but with error messages being contained in the template this means duplicating the error messages likely through extracting them into a component for the form control.  This is fine and dandy, but then the error messages are separated from the validation logic and have to be imported separately.

My suggestion is that we create a messages object in the instance like so:
```
{
    data() {...},
    validations: {
        form: {
            field: {
                required,
                maxLength: maxLength(20)
           }
       }
    },
    errorMessages: {
        form: {
            field: {
                required: 'This field is required',
                maxLength: this.$t('i18n_message_token')
            }
       }
   }
}
````

We would then create a wrapper component for `q-input` which would populate the error slot with validation messages for invalid fields.  This has the advantage that error messages can then be translated as well.  The prototype for a q-input might look something like:

```<validated-input v-model="$v.form.field" error-messages="errorMessages.form.field" />```

This would allow the validation and messages to be encapsulated as a mixin (or imported with the usual javascript/es6 imports to allow pulling in portions of a models validation without needing the entire thing.  Using es6 imports would allow modifications to the validation rules on a per-template basis for situation where, for example a field is required on create, but not during edit.

**Comment by gmeben** [comment]
If I understand this approach correctly, it looks like it offers the best of both worlds in that it enables code re-usability (for validation and messages) and also customization (for messages). Well done.
