### ISSUE TITLE
Discuss Profile Metadata

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#185]
### Problem/Why
There are several metadata properties that are questionable:

1. Humanities Commons and ORCHID ID are not designated as social media
2. Mailing address and phone might not even be necessary
3. If mailing address is necessary, it's missing country
4. Salutation interferes with the purpose of Display Name and might not even be necessary
5. Skype is perhaps incorrectly designated  as social media

### Goal/What
Resolve problems with profile metadata

### Solution/How
Have a discussion with PPJ stakeholders to address problems with current profile metadata

**Comment by sattler9** [comment]
Rewrote the items as questions and sent them along in the email for the agenda with the PPJ Ed team for April 5th's meeting

**Comment by sattler9** [comment]
With April 5th's meeting being postponed to the 15th, Kelly will request that the PPJ ed team respond via email.

**Comment by sattler9** [comment]
I received the following answers...
**### From Kurt:**
## Questions:
1) Should Humanities Commons and Orcid ID be considered as part of the “Social Media” section of a person’s profile?
- I think it makes sense to put HC in the “Social Media” section. What if we just changed that to “Networks” or something else, which would solve the problem of including Skype there.
- The ORCID is a bit different and should likely appear in the “USER” section near username, email, and so on.
 
2) What designation should Skype have? (It is currently designated as Social Media.)
 - no comment
3) Is it necessary to collect:
a) the user’s mailing address? If so, should we add “Country”? - Not necessary to collect. If optional, we should include country.
b) the user’s phone number? - Not necessary.
c) Salutation (it interferes with the purpose of Display Name). - This one seems necessary to me for the purpose of auto-populating emails from the system. If that’s something we’re going to do, we’ll want the template to generate with this salutation as opposed to “Display Name” (e.g., “Dear Dr. Miller” as opposed to “Dear Miller214”)

From Taylor:
1) Should Humanities Commons and Orcid ID be considered as part of the “Social Media” section of a person’s profile? 
- Sure. I think both of these are equivalent to social-professional network spaces like LinkedIn, so putting them under social media makes sense to me.
2) What designation should Skype have? (It is currently designated as Social Media.) 
- Perhaps I'm too much of a millennial for this, but does anyone regularly use Skype anymore? It also seems like a very direct form of contact that I would not want others to access just by viewing my profile. 
3) Is it necessary to collect:
a) the user’s mailing address? If so, should we add “Country”? - I don't see a need for this.
b) the user’s phone number? - I also don't see a need for this.
c) Salutation (it interferes with the purpose of Display Name) - I don't think this adds any essential value to include.

**Comment by wreality** [comment]
Chatted with Kurt, we're in agreement with the following:

1.  Drop Mailing Address
2.  Drop Salutation
3.  Drop Phone
4.  Drop Skype
5.  We'll make a new grouping of metadata for academic profiles and move HC, academia.edu and orchid into them.
