### ISSUE TITLE
Create wireframes for search results page.

### ISSUE THREAD

**Issue by Sruthin86** [MESH-Research/CCR#195]
### Problem/Why

We do not have a design/standard that assists us while implementing the user interface on the CCR app.

### Goal/What

In the interest of having a cohesive and consistent design, create a wireframe to ease the design decisions when implementing the functionality. 

### Solution/How

Use Figma or Adobe XD to create desktop and mobile wireframes. 

### To Do / Acceptance Criteria

- [x] Wireframes for desktop view exists and reviewed by the team.
- [x] Wireframes for mobile view exists and reviewed by the team.
- [x] Redlines exist in the wireframe to assist development

### Review Checklist

- [x] Wireframes for desktop view exists
- [x] Wireframes for mobile view exists

**Comment by Sruthin86** [comment]
Researched Figma and started building a basic wireframe for the desktop view.

**Comment by Sruthin86** [comment]
[https://app.zenhub.com/files/215870675/909f935a-9c3c-4e02-bc17-668d0fa4b967/download](https://app.zenhub.com/files/215870675/909f935a-9c3c-4e02-bc17-668d0fa4b967/download)

**Comment by Sruthin86** [comment]
Attached are the pdf's for desktop and mobile view. The PDF's show different behaviors on the search results page on desktop and mobile screens. Reviewed the wireframes with Grant during team time, and marking the ticket as ready for review.

**Comment by Sruthin86** [comment]
Link for figma desktop wireframe: https://www.figma.com/proto/o6rEskQX8oIUQOdl1QBrBt/CCR-Search?node-id=32%3A153&scaling=min-zoom&page-id=4%3A7

Link for figma mobile wireframe: https://www.figma.com/proto/o6rEskQX8oIUQOdl1QBrBt/CCR-Search?node-id=15%3A357&scaling=scale-down&page-id=15%3A356

**Comment by gmeben** [comment]
I created a Figma account and I've re-reviewed the wireframes. They are in deliverable condition to be discussed in review with PPJ Editorial.

Capturing feedback from yesterday's meeting:

* On grid or mobile layouts, the grid/list elements representing result items can be made less tall by 
    * reducing the size of avatars and re-positioning them so they are horizontally adjacent to usernames
    * reducing vertical negative space between usernames, emails, and display names
* Append numbers to sample usernames to improve their recognizability as sample usernames
* It's important to think about the necessity of implementing controls for toggling between grid and list representations
    * What are the different user needs met by grid and list representations?
    * Does one offer more data than the other? Should it or should it not?
