### ISSUE TITLE
Wireframe User Details Page

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#196]
### Problem/Why
There is currently no page for user details. There is also little established in what content should appear on this page and how it should appear.

### Goal/What
Create a list of content for the user details page and wireframe it.

### Solution/How
Develop a list of content and share this list with the rest of the team for feedback. When agreed upon, begin creating a wireframe mocking the interface for the user details page.

### To Do / Acceptance Criteria

- [x] Create list of content
- [x] Submit list to team for approval
- [x] Once approved, create wireframe

### Review Checklist

- [x] The list of content and expected needs of the user details page has been supplied
- [x] The wireframe file appears complete
- [x] All content on the wireframe fulfills the expected needs of the user details page

### Accessibility Checklist

- [x] Content within the wireframe has an obvious visual hierarchy to inform a document outline

**Comment by gmeben** [comment]
I began my list of content here: https://docs.google.com/document/d/10TzFrmCTwPtR_BtrYtR8o-UqOAHQeH_kSpS4HExwgYk/edit#

**Comment by gmeben** [comment]
I reviewed the list of content in a meeting today with the rest of the team and we are in agreement about the content that should appear on the user details page for administrators.

**Comment by gmeben** [comment]
I've got mockups created for the four breakpoints we currently have implemented. They're in an acceptable state, but I'm not satisfied with them and plan to continue to tweaking them tomorrow morning. I should have a finalized version then.

![mockups.png](https://images.zenhubusercontent.com/5ff7670b9384a948b4663b2d/1d2383a0-07f3-4c34-9437-d88fdcd2d23b)

I would say the estimate of this card has changed from a 2 to a solid 5.

**Comment by gmeben** [comment]
Attached are the deliverable mockups.

[https://app.zenhub.com/files/215870675/b90d6fce-1e9c-47fb-b5aa-f829996f1ecd/download](https://app.zenhub.com/files/215870675/b90d6fce-1e9c-47fb-b5aa-f829996f1ecd/download)

**Comment by gmeben** [comment]
On Monday, I plan on implementing the feedback and suggestions from the team during today's meeting. 

**Changes**

- Use different helper icons to represent administrators
- Add a section for Publications
- Combine the Roles and Publications sections into a Tabs component

**Comment by gmeben** [comment]
Here are the links to preview the mockup prototypes:

**Sections**

* Icon Set 1 - https://xd.adobe.com/view/8d0aff01-72ea-4b69-ac8d-a0ba70e082d1-d859/
* Icon Set 2 - https://xd.adobe.com/view/398d5b99-9239-485c-ad9f-ff3ed5d42dfc-6cde/

**Tabs**

* Icon Set 1 - https://xd.adobe.com/view/4e4265f0-0992-4eb9-93aa-30976e4b202e-1b11/
* Icon Set 2 - https://xd.adobe.com/view/4f17b02d-21d3-42b1-9f5e-fe8262316b1c-1a44/

**Comment by sattler9** [comment]
We bumped the estimate from a 2 to an 8 because the scope expanded from a wireframe to a prototype and an exploration of Adobe AD. There were also multiple full team reviews.
