### ISSUE TITLE
Create wireframes for In-App Notifications

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#319]
### Problem/Why
Users do not have a way to interact with notifications.

### Goal/What
The interface should:
  - indicate if the user has pending notifications, 
  - allow them to view the pending notifications
  - Dismiss/mark-as-read the notifications.
  - View previous read notifications

### Solution/How
Create/Edit an in browser prototype to show how the user interface should be modified to include notifications.  Leverage existing quasar UI elements as much as possible / practical.  Research existing notification strategies and interfaces.

### To Do / Acceptance Criteria

- [x] Wireframe is approved by the CCR team
- [x] Design follows best practices for accessibility, UI/UX.
- [x] Design patterns flow with existing design patterns

**Comment by sattler9** [comment]
Note: prototyping in the browser is the way Brian intends to do going forward

**Comment by wreality** [comment]
"Feed" page (view more page) is complete and looks like this:

![image.png](https://images.zenhubusercontent.com/5fe17935da86cae135bcd2ab/adc4e323-1bb0-482a-9491-8efc0a5878af)

![image.png](https://images.zenhubusercontent.com/5fe17935da86cae135bcd2ab/a10d3f20-2db0-4a11-9925-10c5547338b9)

**Comment by wreality** [comment]
PR #713 is open for review
