### ISSUE TITLE
Set Up Sanctum

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#32]
**Problem/Why**

There is currently no way for users to authenticate from the client to the backend on CCR. It would be costly to develop an authentication system from scratch.

---

**Goal/What**

Implement Sanctum as an authentication system to handle user logins.

---

**Solution/How**

Install Laravel Sanctum as a Composer dependency: https://laravel.com/docs/8.x/sanctum#installation

---

### To Do - 2021-01-11

Backend
- [x] Setup Sanctum Lighthouse middlewares (Lighthouse Docs)
- [x] Create login mutation in lighthouse (Lighthouse Docs)
- [x] Create a mock user (Laravel tinker)
- [x] Test using /graphql-playground login mutation

Client
- [x] Extend login form to use apolloclient/graphql login endpoint
- Answer question: How is logged in state stored?

### To Do - 2021-01-05

- [x] Install Laravel Sanctum as a composer dependency 
- Test if Sanctum is installed correctly and works as expected  
- Configure Sanctum as described in the Laravel documentation 

### Review Checklist 
- [x] Sanctum issues a cookie to mitigate CSRF 
- [x] Sanctum issues a session cookie when successfully authenticated 
 
## Attachments 
 
- [Is child to System User Authentication](https://trello.com/c/XK8oNtaj/11-system-user-authentication#sf-dependencies&dependencyType=is_child_to&dependencyId=5f68d540d839a876b6bc7551&resolved=false) 
 
> Trello Source: https://trello.com/c/ICQyqnbW

**Comment by gmeben** [comment]
Here is the code I used to test authentication for a user I generated with faker:

```graphql
query GetUser {
  user(id:1){
    id
    email
    name
  }
}

mutation Login {
  login(email:"xrau@example.net",password:"password") {
    id
    email
    name
  }
}

mutation Logout {
  logout {
    id
    email
    name
  }
}
```

**Comment by gmeben** [comment]
Brian helped me complete the final task for hooking up the Apollo Client-based web form to the Sanctum-based authentication backend.

I'm moving this to the Review column for now, but additional research will need to be done to determine how logged in state is stored on the client.

**Comment by gmeben** [comment]
I will be creating a pull request shortly for both Sruthin and Brian to review and the remaining items in the Review Checklist will be addressed then.

**Comment by gmeben** [comment]
Although this issue was estimated as a 5 (medium) the effort involved in this body of work felt more like somewhere between an 8 (large) or a 13 (larger) because it took all sprint and required help from my teammates.
