### ISSUE TITLE
Toggle Publication Visibility Status 

### ISSUE THREAD

**Issue by Sruthin86** [MESH-Research/CCR#321]
### Problem/Why
Currently there is no way to toggle the visibility status of a publication. 

### To Do / Acceptance Criteria

- [ ]

### Review Checklist

- [ ]

### Accessibility Checklist

- [ ]

**Comment by gmeben** [comment]
The purpose of this issue was addressed on June 23rd, 2022 in [this file](https://github.com/MESH-Research/CCR/blob/78ef8ae04f1b244f62035e8731fbd6aa1fc237ed/client/src/components/forms/Publication/UpdateBasicForm.vue) of [this pull request](https://github.com/MESH-Research/CCR/pull/1230/files).
