### ISSUE TITLE
Documentation for development under WSL

### ISSUE THREAD

**Issue by amareshjoshi** [MESH-Research/CCR#327]
**Is your feature request related to a problem? Please describe.**
Setting up CCR development using WSL is complicated and developers will be helped by a setup guide

**Describe the solution you'd like**
Create a page with instructions and tips for setting up for development under WSL
and link it into the main documentation.

** Steps**
- [x] Determine steps to setup dev environment under WSL
- [x] Test setup steps
- [x] Create WSL dev setup page and link to the rest of the documentation

** Review 
Examine changes to the docs on branch issue327-dev-setup-for-wsl

**Comment by Sruthin86** [comment]
Gitlab pull requests: https://github.com/MESH-Research/CCR/pull/389
**Next steps:**
- Fix the link issues in the markdown files.
- Fix the commit message formatting.
