### ISSUE TITLE
Dependabot PHP Pull Requests

### ISSUE THREAD

**Issue by amareshjoshi** [MESH-Research/CCR#366]
Initial Steps

- [x] create a new branch from development (issue366-dependabot-php)

Process pending PHP requests

- [x] 331
- [x] 337
- [x] 345
- [x] 346
- [x] 347
- [x] 358

Final steps
- [x] test locally
- [ ] create pull request to merge back to development

**Comment by Sruthin86** [comment]
GitHub pull request: https://github.com/MESH-Research/CCR/pull/392
**Next steps:**
- Fix the merge conflicts. 
- Check/Fix commit message format.
