### ISSUE TITLE
Incorrect label on login page

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#4]
The field label for username is "Username of Password" and should be "Username or Email"

**Comment by jackei1989** [comment]
Hello
I think you want to change that: <q-input square v-model="form.username" label="Username or Password">
If I think about it, let me work on it!

**Comment by jackei1989** [comment]
Hello
I think you want to change that`<q-input square v-model="form.username" label="Username or Password">`
if its true, may i work on this?

**Comment by wreality** [comment]
Go for it. PR’s welcome.
