### ISSUE TITLE
Design submission details pages with add reviewers functionality

### ISSUE THREAD

**Issue by Sruthin86** [MESH-Research/CCR#400]
### Problem/Why
Page design and layout for adding reviewers to a submission does not exist.

### Goal/What
Design a frontend interface using quasar to demonstrate the UI of the add reviewers workflow. 

### Solution/How
Use the existing quasar components and create a frontend interface. 
Components used 
```
q-item
q-select
```

### To Do / Acceptance Criteria

- [x] Create a new view for the Submissions page.
- [x] Add a h3 for the dropdown.
- [x] Add and h3 for reviewers section
- [x] Create a dropdown to demonstrate the addition of reviewers to a submission.
- [x] Create a list to display the added reviewers.
- [x] Add a user avatar in the list.
- [x] Add email address under the display name. 

### Review Checklist

- [x] Page layout matches the existing design(Submissions and Publication page).
- [x] Page is reviewed by the team at post stand-up.

### Accessibility Checklist

- [x] Passes axe accessibility checks

**Comment by Sruthin86** [comment]
Roles spreadsheet: https://docs.google.com/spreadsheets/d/1j6TUtNlN_nM6TNpZtCOMCU8i7HJ8dVJCUI4RfcUkQuc/edit#gid=0

Rows in question: #56, #57

Discuss the permissions with Kurt the next time we talk to him

**Comment by sattler9** [comment]
Kurt thought the update to the spreadsheet made sense.

**Comment by Sruthin86** [comment]
**Feedback from standup**
- Add a trash can icon next to the reviewer
- Add a h3 for the dropdown.
- Add and h3 for reviewers section.
- Adjust the padding and spacing on the two column layout
- Change the styling of the button and use "ADD"
- Add a user avatar in the list. 
- Add email address under the display name.

Change this ticket to a design in browser ticket. Make new tickets to implement the functionality of the remaining items that are taken out.

**Comment by Sruthin86** [comment]
**Feedback from team**

- Use "Assigned Reviewers" as h3.
- Replace the trash icon with a minus.

**Comment by Sruthin86** [comment]
Previous version of this ticket 
### Problem/Why
There is no way for assigning reviewers to submissions.


### Goal/What
Review Coordinators, Editors, Publication Administrators, and Application Administrators should be able to assign reviewers. 

### Solution/How
Create a manage page which can be accessed by Review Coordinators, Editors, Publication Administrators, and Application Administrators to assign reviewers.


### To Do / Acceptance Criteria

- [x] Create a new view for the Submissions page.
- [ ] Add elements to the interface for adding multiple reviewers and review it with the team.
- [ ] A manage button appears next to the submissions for Review Coordinators, Editors, Publication Administrators, and Application Administrators.
- [ ] The new view/page can only be accessed by Review Coordinators, Editors, Publication Administrators, and Application Administrators.
- [ ] Add to GraphQL schema to enable the association of reviewers. 
- [ ] Jest and Cypress tests exists.
- [ ] PHP unit test exits to ensure only  Review Coordinators, Editors, Publication Administrators, and Application Administrators can add reviewers. 

### Review Checklist

- [ ] Manage button is available to Review Coordinators, Editors, Publication Administrators, and Application Administrators for each submission.
- [ ] Review Coordinators, Editors, Publication Administrators, and Application Administrators should be able to assign reviewers.
- [ ] Other users will not be able to visit the manage page or assign users .
- [ ] PHP unit tests pass.

### Accessibility Checklist

- [ ] Passes axe accessibility checks

**Comment by Sruthin86** [comment]
Stand-up decisions
- Change the heading from "All Reviewers" to "Assigned Reviewers".
- Include "Manage: " in the submission title heading.
- Email wrapping issues on tablet size screen.

**Comment by gmeben** [comment]
I submitted a review here: https://github.com/MESH-Research/CCR/pull/458#pullrequestreview-715269294
