### ISSUE TITLE
Replace spatie/permissions with JosephSilber/Bouncer

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#401]
### Problem/Why
Spatie/Permissions doesn't allow assigning of permissions to models and/or entities which is an important characteristic for upcoming features of the application.

### Goal/What
We should be able to assign permissions based on global, associated to a model or class, and to a specific entity of a model or class.

### Solution/How
Replace spatie/permission with josephsilber/bouncer which does allow for the assigning of more descriptive permisisons.

### To Do / Acceptance Criteria

- [ ] Create a migration to remove the spatie tables
- [ ] Add bouncer and related migrations 
- [ ] Add new permission migration to match current role needs
- [ ] Update graphql routes for returning users abilities and roles
  - [ ] Should return flat array of each
  - [ ] For abilities use the format ($ability) ($ability:$model) or  ($ability:$model:$entityId) as appropriate.
- [ ] Update graphql @can directives to use related model and remove model policies
- [ ] Update existing tests with any API changes.

### Review Checklist

- [ ] Existing tests pass.
- [ ] Graphql users query returns flat array for abilities and users.

### Accessibility Checklist

No accessibility concerns

**Comment by wreality** [comment]
I'm going to hold back on this for a hot minute until we can discuss in team time.  I'm realizing it definitely solves one set of problems nicely, but it doesn't impact the core permission need we'll have: assigning a role to a user on a model instance.  Neither package does that, and that may be just where we're left implementing our our logic for "this user has reviewer role on x submission which grants them these abilities".

Bouncer would let us say this user has x, y, z ability on submission a

Here's a good article on the two packages:

https://laravel-news.com/two-best-roles-permissions-packages

**Comment by gmeben** [comment]
@wreality I think I see what you're talking about. It appears Bouncer still has the same global limitation with roles that Laravel-permission does.

What we need is to be able to assign a user a role per model, and the role will give that user a class of permissions for a particular model only. We don't just need role-based access control; we need _model-relative_ role-based access control or what I imagine might be called attribute-based access control. https://en.wikipedia.org/wiki/Attribute-based_access_control

It almost looked like Bouncer is capable of supporting this from looking at its database tables, but I'm not able to figure out how it's possible, and their API documentation doesn't demonstrate that this is possible either.

**Comment by wreality** [comment]
The other thing we could do is wrap our publication and submission roles around bouncer. 

In vague terms, 

If a user is granted a publication role on publication y, we grant permission x,y,z on that publication instance. Then we'd still have the ability to use the built in gates to check "can user x do this on this publication?" But essentially we'd handle managing the hierarchical relationship of publication and submissions ourselves. 

I'm just thinking it's better to keep the permission checking as close to the core of Laravel as we can to avoid having to create messy queries just to check if a user can do a thing.

**Comment by wreality** [comment]
Moving to next sprint.

**Comment by sattler9** [comment]
As we've been building out customer code, this won't benefit us enough to do it.
