### ISSUE TITLE
Update vue-apollo to version 4

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#412]
### Problem/Why
The current version of vue-apollo does not provide the composition API. :-( The composition API will help make portions of our code more reuseable.

### Goal/What
Provide developer access to the composition API. 

### Solution/How

Remove quasar-app-apollo and integrate vue-apollo@4 directly.  vue-apollo@4 is compatible with Vue v2.  quasar-app-apollo@next provides vue-apollo@4, but requires quasar@v2 which we aren't ready to upgrade to.

### To Do / Acceptance Criteria

- [x] Remove `@quasar/apollo` extension using the quasar-cli
- [x] Install `graphql graphql-tag and @apollo/client`
- [x] Follow [options API installation docs](https://v4.apollo.vuejs.org/guide-option/setup.html#_1-install-vue-apollo-option) to ensure compatibility with out current code.
- [x] Follow [composable-api installation docs](https://v4.apollo.vuejs.org/guide-composable/setup.html#_1-install-vue-apollo-composable)
- [x] Ensure existing tests pass.
- [x] Update `page/admin/UsersIndex.vue` to utilize the composition API
- [x] Update tests as needed to pass

### Review Checklist

- [ ] All tests pass
- [ ] Code review

### Accessibility Checklist

No accessibility issues.

**Comment by wreality** [comment]
Moved back to review as there are some testing issues that need to be worked out.

**Comment by wreality** [comment]
Still working through testing issues although I think I've figured out how at least to setup the tests.  There's a few lingering cypress errors that have popped up as well mostly related to the vuelidate upgrade.

**Comment by sattler9** [comment]
might have under estimated effort due to testing part

**Comment by wreality** [comment]
I increased the estimate on #413 to account for the increased effort required.
