### ISSUE TITLE
Install vue/composition-api

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#413]
### Problem/Why
There are challenges and drawbacks with re-using code with the traditional approaches available in Vue 2 (i.e. mixins, mixin factories, scoped slots).

### Goal/What
Implement the vue2 composition api to improve the reuse of code in an organized, maintainable way.  

### Solution/How
The vue2 composition api is compatible with our current quasar.  Install and configure the composition api.

### To Do / Acceptance Criteria

- [x] Install the @vue/composition-api: https://github.com/vuejs/composition-api
- [x] When instructed to add Vue.use(VueCompositionApi) read [QuasarCLI/boot files](https://v1.quasar.dev/quasar-cli/boot-files#introduction)
- [x] Ensure that all tests remain passing.
- [x] Ensure existing tests pass.
### Review Checklist

- [ ] Existing tests pass

### Accessibility Checklist

No accessibility concerns.

**Comment by gmeben** [comment]
I changed the description to better adhere to the problem/goal/solution format. Feel free to make adjustments if anything's inaccurate.

**Comment by wreality** [comment]
Works for me!

**Comment by wreality** [comment]
Updated the estimate as it turns out figuring out jest testing was a bigger chore than expected.
