### ISSUE TITLE
Incorporate Nested Mutation into Submission Creation

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#491]
### Problem/Why
In GraphQL, there are certain mutation operations that require the creation of both records and pivot table entries. Currently, these are created in multiple operations via chaining, which can lead to records being created and necessary pivot table records not being created (ex: Submissions without SubmissionFiles or Submissions without SubmissionUsers).

### Goal/What
Make the creation of Submissions such that the creation of records that are interdependent (SubmissionUsers, SubmissionFiles) are done simultaneously in a single operation.

### Solution/How
Using the documentation for Lighthouse (https://lighthouse-php.com/5/eloquent/nested-mutations.html), refactor Laravel models and GraphQL operations/files/schema as necessary for nested behavior.

### To Do / Acceptance Criteria

- [x] Refactor code to support nesting for submission creations
- [x] Add and refactor tests as necessary

### Review Checklist

- [x] All existing tests pass

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/491?planning-poker) with ZenHub @gmeben @wreality
