### ISSUE TITLE
documentation for style guide

### ISSUE THREAD

**Issue by sattler9** [MESH-Research/CCR#493]
### Problem/Why
As developers, we lack documentation to reference for styles, which requires us to search for decisions or redecide what we should do.

### Goal/What
To have a document that contains decisions made up to this point that are easy to find and reference that can be continually expanded as more decisions are made.

### Solution/How
Make the document and populated them with styles that we've already have committed to. Have the document linked in areas where we're tracking CCR documentation.

### To Do / Acceptance Criteria

- [x] Decide where the document will be kept / what platform
- [x] Make the document
- [x] Layout potential structure
- [x] Link the new documents in [Trello board](https://trello.com/b/Qeo5A2Qe/ccr-backlog), [Github wiki page](https://github.com/MESH-Research/CCR/wiki/CCR-Links)

### Review Checklist

- [ ] Team reviews document
- [ ] Team decide if alternate platform would be better

**Comment by sattler9** [comment]
inspiration https://docs.google.com/document/d/124gG6INJs5Aqk407ynzj8JWHeMBDfpaqb1rput7FDsQ/edit?usp=sharing

**Comment by sattler9** [comment]
Much discussion on is this 1 or 2 "documents"  - editorial vs user interface
Options on where we might store our decisions. May choose multiple options:
- UI in its own Quasar site
- a document on github wiki
- google doc
- an HTML website

**Comment by gmeben** [comment]
The direct updates to the development branch that @sattler9 performed to address this issue have been merged into the master branch as of this morning.
