### ISSUE TITLE
Assign/Unassign reviewers to submissions

### ISSUE THREAD

**Issue by Sruthin86** [MESH-Research/CCR#496]
### Problem/Why
Currently the assigned reviewers via the user search dropdown is not saved in the db, and the controls for unassigning the user are non-functional.

### Goal/What
Reviewers can be successfully assigned and unassigned to a submission.

### Solution/How
Save the assigned reviewers in the db and display them in the list on the manage submissions page.

### To Do / Acceptance Criteria

- [x] Add mutation to create submission users.
- [x] Assigned reviewers are displayed on the manage submissions page
- [x] The button which unassigns reviewers is functional
- [x] An error message appears when the user attempts to assign a duplicate reviewer to a submission
- [x] Jest and Cypress exists.
- [x] PHP Unit tests exits.

### Review Checklist

- [x] Reviewers are displayed on the manage submissions page
- [x] Jest and Cypress tests pass
- [x] PHP Unit tests pass

### Accessibility Checklist

- [x] Passes axe accessibility checks

**Comment by gmeben** [comment]
I was able to get the unassignment button working, however, the reviewer list is no longer filtering reviewers correctly.

As for the error message, the closure containing where clauses in the Lighthouse Validator is not being recognized. I've created a question on StackOverflow seeking help: https://stackoverflow.com/questions/68964716/multiple-unique-columns-with-a-lighthouse-validator-class

**Comment by gmeben** [comment]
The estimate for this issue has become between an 8 or 13. Half was completed during Sprint 18. The remaining estimated half will be worked upon in Sprint 19.

**Comment by gmeben** [comment]
I fixed the issue related to reviewers not being filtered correctly. The fix almost seems indicative of a bug on the part of Vue or Vue Apollo, but it's also possible that there's some configuration of caching behavior on the App that is misconfigured.

**Comment by gmeben** [comment]
I added generic error message notification functionality on the client side since I'm still not yet able to get error messages for duplicate entry attempts successfully sent from the server side. The UX is acceptable.

**Comment by gmeben** [comment]
All that remains is adding a Cypress assertion for a duplicate reviewer assignment attempt and this will be ready for review tomorrow.
