### ISSUE TITLE
Set Uploading User as Submitter By Default

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#501]
### Problem/Why
Upon the creation of a new submission, no user is designated as the submitter, not even the user creating the submission.

### Goal/What
Upon a submission creation, designate the creating user as the submitter by default.

### Solution/How
Update the submission creation mutation to synchronously issue a nested mutation to add a pivot table entry with the creating user designated as the submitter.

### To Do / Acceptance Criteria

- [x] Add a nested mutation for setting the creating user as a submitter
- [x] Add a Cypress test to check that the creating user is listed as a submitter

### Review Checklist

- [x] The user who creates a submission is designated as the submitter by default

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/501?planning-poker) with ZenHub @gmeben @wreality

**Comment by gmeben** [comment]
The first half of this issue was addressed in issue #491. 

What's missing is adding an assertion in Cypress, which is a trivial task.
