### ISSUE TITLE
Research Pandoc

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#517]
https://github.com/ueberdosis/pandoc

https://github.com/jgm/pandoc

## Questions to Answer

1. Are there any filetypes that CCR intends to support that Pandoc doesn't?
2. What is the output of a file converted by Pandoc for each filetype that CCR intends to support?
3. Describe the probable backend process for submissions being processed by pandoc (pseudo-code AT MOST).

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/517?planning-poker) with ZenHub @gmeben @stephanievaskomsu @wreality

**Comment by gmeben** [comment]
# Answer to Question 1

Pandoc will support all the text-based file formats that we're currently interested in supporting. Most multimedia formats (video, audio, image) are not supported. `.pptx` is supported. `.doc` is not listed as one of those supported, but `.docx` is. `.txt` is also unlisted, however, it is possible to output to `Plain text` format in the [Pandoc online demo](https://pandoc.org/try/) which is equivelant to `.txt`. 

**Unsupported**

1.  aiff
2.  avi
3.  doc
4.  gif
5.  jpg
6.  m4a
7.  m4v
8.  mov
9.  mp3
10. mp4
11. ods
12. png
13. svg
14. tiff
15. tsv
16. wmv
17. xls
18. xlsx

**Supported**

1.  csv
2.  docx
3.  html
4.  odp (listed as \"odt\")
5.  pdf
6.  pptx
7.  txt (listed as \"Plain text\" in demo)

**Bonus Supported**

1. docbook
    - https://tdg.docbook.org/tdg/5.2/ch01.html
2. epub
3. latex
4. md
5. rtf

Source: https://pandoc.org/MANUAL.html#option--to

**Comment by gmeben** [comment]
# Answer to Question 2

Outputs can be tested on the fly here: https://pandoc.org/try/

Pandoc's output is generally consistent with my expectations. I haven't observed anything alarming in my tests so far, although I haven't yet tested most of the listed file formats.

**Comment by gmeben** [comment]
# Answer to Question 3

My current understanding is that once the [PHP Pandoc wrapper](https://github.com/ueberdosis/pandoc) and the [Docker image](https://pandoc.org/installing.html#docker) are installed, conversions can take place using code like the following from the GitHub repo's README:

```php
$output = (new \Pandoc\Pandoc)
    ->from('markdown')
    ->inputFile('path/to/stored/file/example.pdf')
    ->to('html')
    ->run();
```

****

The way I'm currently imagining this working: this code will run either upon completion or at the time of the `CreateSubmission` mutation on the backend. Once the uploaded file is determined to be a manuscript, Pandoc can be used to convert the file's contents to HTML and this `$output` can be stored in the database and associated with the newly created submission.

**Comment by gmeben** [comment]
One of the findings we did as a team today was an unfortunate discovery that, while Pandoc supports outputting to PDF, it does not support inputting PDFs for conversions.
