### ISSUE TITLE
Show Submitters on Submission Details Page

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#555]
### Problem/Why
Currently, the submission details page does not display submitters.

### Goal/What
Add a new "Submitters" section  and show a list of the submitters (as is currently done for assigned reviewers)

### Solution/How
Update the SubmissionDetails.vue file with the necessary markup for a Submitters section. Utilize the data from Vue Apollo to create a new computed property for supplying a list of submitters to the new section. Begin creating reusable components for the necessary elements where able.

### To Do / Acceptance Criteria

- [x] A new section is added for submitters
- [x] The new section contains a list of assigned submitters
- [x] Add necessary Jest assertion to check that submitters appear in the list of submitters

### Review Checklist

- [x] All existing and new tests pass

### Accessibility Checklist

- [x] The list provides screen reader announce-able items that are easy to understand
- [x] Text is legible and uses terminology that is easy to understand
- [x] There are no color contrast issues

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/555?planning-poker) with ZenHub @gmeben @wreality

**Comment by gmeben** [comment]
The component refactoring took me a bit longer than I expected because I didn't anticipate how doing that would affect (read: improve) the Jest test spec.
