### ISSUE TITLE
Internal user creation

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#60]
**Problem/Why**

Users cannot register an account.

---

**Goal/What**

Users should be able to create a local account (not including social sign-on).

---

**Solution/How**

Implement front-end pages and API endpoints to allow a user to register.  Input data should be validated on both the front-end and backend and appropriate feedback should be provided to users.

** Schema **
```
Query {
   userCreate(name: String!, email: String!, password: String!): User!
}
```
Validation Criteria:

- Name: required
- Email: required, valid email, unique
- Password: required, zxcvbn at least 5 (?)

Password should be validated on both frontend and backend.  Live feedback should be provided to users regarding the strength of their password.

Laravel zxcvbn library: https://github.com/olssonm/laravel-zxcvbn

--- 
### Review Checklist 
- [ ] Users can register an account 
- [ ] Submitted data is validated properly. 
- [ ] UI/Flow follows best-practices and provides for excellent User experience. 
### To Do 
- [x] Configure apollo-client to communicate with the laravel API 
- [ ] Add tests as appropriate 
 
> Trello Source: https://trello.com/c/M3LP21fR

**Comment by Sruthin86** [comment]
The developers worked together on the implementing the GraphQL schema for user creation. Code is checked in and a pull request created. 
MESH-Research/CCR: Pull Request 94
