### ISSUE TITLE
Setup the connection between Apollo Client and Lighthouse

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#62]
**Problem/Why**

There is currently no way for the frontend and backend to communicate with one another on CCR.

---

**Goal/What**

The frontend and backend applications need a way to communicate with each other. Connecting Apollo Client and Lighthouse alleviates the problem. Ensure successful data transfer between the frontend and backend apps.

---

**Solution/How**

--- 
## Attachments 
 
- [Is child to System User Authentication](https://trello.com/c/XK8oNtaj/11-system-user-authentication#sf-dependencies&dependencyType=is_child_to&dependencyId=5f68d540d839a876b6bc7551&resolved=false) 
 
> Trello Source: https://trello.com/c/kYJzyych

**Comment by wreality** [comment]
There's honestly not much to review here since it seems most of the work had already been completed, but still could @gmeben or @Sruthin86 give PR #89 a look over and mark it ask reviewed please & thanks.

**Comment by gmeben** [comment]
@wreality I approved pull request #89
