### ISSUE TITLE
Refactor References to Roles Model

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#643]
### Problem/Why
There are hardcoded static references of IDs pertaining to roles throughout the codebase, which creates tech-debt. While there are constants defined in the Roles model to mitigate this, they are not consistently used throughout the codebase.

### Goal/What
Refactor static references to role IDs to instead use the defined constants in the Roles model. 

### Solution/How
Find and replace all occurrences of static ID references. 

### To Do / Acceptance Criteria

- [x] Replace all static ID references

### Review Checklist

- [x] There are no static ID references missed

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/643?planning-poker) with ZenHub @gmeben @wreality @stephanievaskomsu

**Comment by gmeben** [comment]
The velocity of this issue felt more like a `1` because it took me less than a day from start to finish and there were surprisingly not that many lines of code that needed to be modified.
