### ISSUE TITLE
Notification Triggers

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#696]
### Problem/Why
Currently, there's nothing defined within CCR as far as what events trigger what notifications to be created. Documents outside of CCR have been created to begin to define some of the foreseen notifications and their triggers:

* [Notifications Map](https://docs.google.com/spreadsheets/d/1TLwnFgY18195whgm-ylFc0Z5UCIG6adPNy5tJIOnbhc/edit#gid=0)
* [Actions by Role](https://docs.google.com/spreadsheets/d/1j6TUtNlN_nM6TNpZtCOMCU8i7HJ8dVJCUI4RfcUkQuc/edit#gid=0)
* [Notes for Notifications Map](https://docs.google.com/document/d/1i6QhM09vSOmJBaT2T2sHlROPRysDoEqxZGhZE5XobEA/edit)

### Goal/What
Define the different types of triggers on both the client and backend to handle notifications triggered by user actions and chronological progression. 

### Solution/How
Expand upon the documents linked to this issue. Have a review meeting with the CCR Development team to review and make changes.

### To Do / Acceptance Criteria

- [x] Expand upon documents

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/696?planning-poker) with ZenHub @Sruthin86 @wreality @gmeben

**Comment by gmeben** [comment]
The criteria for achieving mutual understanding of notifications between all team members has been removed from this issue. The related spreadsheet has been updated sufficiently to enable initial development on the first notification type (submission creation). It answers the questions of who should initiate the notification (by role), who should be the notification recipients (by role), and how they should receive a notification.
