### ISSUE TITLE
Handle Notification Read Statuses

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#700]
### Problem/Why
There is currently no implemented way for in-app notifications to be indicated as read by a user. Users may annoyingly encounter the same notifications when navigating throughout CCR with no way to mark notifications as read and dismiss them.

### Goal/What
Implement a way for users to mark notifications as read.

### Solution/How
Define user interaction behavior for marking notifications as read. Research strategies for implementing read status demarcation (https://laravel.com/docs/8.x/notifications#marking-notifications-as-read) via user interaction, using Lighthouse if possible. Update code as necessary on the client and the backend. 

### To Do / Acceptance Criteria

- [x] Create a mutation to update the read status for an individual notification
- [x] Have a guard in place to ensure that only the current user can update their read status
- [x] Create a "mark all read" mutation to update the status of all the notifications
- [x] Add interaction on the UI to enable marking notifications as read
- [x] Add PHPUnit tests (as necessary)
- [x] Add Jest testing to make assertions about notifications being read and unread 
- [x] Add Cypress testing to assert that notifications can be marked as read individually
- [x] Add Cypress testing to assert that multiple notifications can be marked as read simultaneously 

### Review Checklist

- [ ] All new and existing tests pass

**Comment by Sruthin86** [comment]
Only update the notification as read on which an action is performed on. Notification grouping or updating the statuses of related notifications will be done in a different ticket

**Comment by Sruthin86** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/700?planning-poker) with ZenHub @amareshjoshi @gmeben @sattler9 @wreality
