### ISSUE TITLE
send email notification to submitter upon receiving a submission

### ISSUE THREAD

**Issue by sattler9** [MESH-Research/CCR#716]
### Problem/Why
A submitter doesn't know if the submission was received since they haven't been notified.

### Goal/What
An email notification will be sent to the submitter's email address as found within CCR that will contain static text within the code saying "Thank you for your submission. It has been received by {publication}."

**Describe alternatives you've considered**
An alternate would be to let the email be editable by the publication editor. This is planned for a later version.

### To Do / Acceptance Criteria

- [ ]

### Review Checklist

- [ ]

### Accessibility Checklist

- [ ]

**Comment by gmeben** [comment]
@sattler9 Since submitters are now notified (via email and in-app) when their submissions are submitted for review and when they're accepted for review, and these notifications can include an optional custom comment from users submitting or accepting, is this issue still relevant?

**Comment by sattler9** [comment]
it depends. The "submitted for review" may be what this ticket is talking about, which is a notification, ideally in-app and via email, that the item the submitter would like to see published has been successfully uploaded into the application.

**Comment by gmeben** [comment]
@sattler9 Yes, that's how it's currently working.

**Comment by sattler9** [comment]
Then this ticket has been completed.
