### ISSUE TITLE
Populate Client with In-App Notifications from Database

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#728]
### Problem/Why
Users cannot see their notifications when logged in. While notifications are now stored in the database, provided on the GraphQL endpoint, and the frontend has been updated to support the the display of notifications, the connection between the client and the GraphQL endpoint has not yet been made to populate a user's interface with notifications.

### Goal/What
Make a user's notifications visible on the frontend. If a notification is stored in the database for a user, that user should be able to view that notification when logged in. 

### Solution/How
Add client code as necessary to retrieve notifications from the GraphQL endpoint. Update the Vue files as necessary to store the notification data in a manner that will allow the new notification UI components (the header component and the dedicated page) to display the currently authenticated user's notifications. 

### To Do / Acceptance Criteria

- [x] Add a new query to `queries.js` for getting the currently authenticated user's notifications
- [x] Add limited notification data to the `currentUser` query in `queries.js` 
- [x] Add code on the client to store and display notification data
- [x] Add Jest testing for showing an expected number of notifications based on mocked data

### Review Checklist

- [x] Notifications that are associated with the currently authenticated user appear in the header component
- [x] Notifications that are associated with the currently authenticated user appear on the dedicated notification page
- [x] Notifications that are not associated with the currently authenticated user do not appear anywhere
- [x] All current tests and the new Jest test spec successfully pass

**Comment by Sruthin86** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/728?planning-poker) with ZenHub @gmeben @wreality @amareshjoshi @sattler9

**Comment by gmeben** [comment]
After discussing in today's team time, a consensus was reached to use a static approach for referenced names in notifications. 

On a separate but related note, our discussion evolved into exploring the same name reference problem but as it would pertain to the audit or activity log of a submission. There are different considerations to be made for the purposes of an audit log and so we did not achieve a consensus for using the same static approach as a solution to this matter.

**Comment by gmeben** [comment]
After team time yesterday, we affirmed that the scope of this issue is limited to showing notifications from the database only. I will create a separate issue for listening to events to trigger the population of notification data in the database.
