### ISSUE TITLE
Populate Database with Notification Data Upon Events

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#746]
### Problem/Why
Currently, there are no events or actions that can be performed within the application to cause notification data to populate in the database. This means that notification data has to be mocked via Tinker commands in order to be populated in the database and allow notifications to appear within the application for a user. 

### Goal/What
Implement an event/listener pattern so that certain actions that are performed in the application cause notification data to be populated in the database. The first event that should do this is the creation of a submission. 

### Solution/How
Add backend code as necessary to for implementing a new event and listener for submission creations. The naming of these files should maintain the "past tense verb" format established for notifications. Add and modify code as necessary to ensure that both an email notification and a database notification are sent to the correct recipients. The correct recipients are the submitter and all editors of the submission's publication. Add an event dispatcher directive for the mutation that handles submission creations in the GraphQL schema. 

https://laravel.com/docs/8.x/notifications#notification-events

### To Do / Acceptance Criteria

- [x] Implement new event and listener for submission creations
- [x] Add code in the listener to notify the correct users for a created submission
- [x] Add event dispatcher for the submission creation mutation in the GraphQL schema 
- [x] Add Cypress test to check that notifications appear for a user

### Review Checklist

- [ ] Creating a submission notifies editors of the submission's publication
- [ ] Creating a submission notifies all submitters of the submission
- [ ] All existing and new testing passes succesfully

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/746?planning-poker) with ZenHub @amareshjoshi @gmeben @Sruthin86 @wreality

**Comment by gmeben** [comment]
Event/Listener Documentation for Notifications in Laravel: https://laravel.com/docs/8.x/notifications#notification-events
