### ISSUE TITLE
Determine Fitness for Review

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#754]
### Problem/Why
According to the ["Submission workflow" Miro board](https://miro.com/app/board/o9J_l654lxo=/), a submission is meant to be evaluated for its fitness for review before being able to be reviewed by reviewers. This is currently not possible in CCR.

### Goal/What
Immediately after a submission is created, implement a way for editors to designate if a submission is fit for review. These should be the allowed choices: 

1. Accept
2. Request Resubmission
3. Reject

Reviewers should be prevented from reviewing the submission until this fitness for review designation is made by an editor. 

### Solution/How
Update Vue templates according to the wireframes in issue #1271

Add mutation functionality to interact with the API that changes the status of the submission based on which of the following options is selected:

* Accept > Awaiting Review
* Request Resubmission > Awaiting Resubmission
* Reject > Rejected

Update the Vue template so that the button that allows a user to review the submission is only interactive to reviewers when the submission is accepted for review. Ensure this permission checking is also on the route to prevent direct access via URL.

### To Do / Acceptance Criteria

- [x] Update the template files (interactive elements, notifications)
- [x] Add mutation functionality for changing the submission status on the GraphQL API from the client
- [ ] ~~Add permissions for viewing a submission out of review~~
- [x] Add permission checking rules to prevent unauthorized access from reviewers
- [x] Add Cypress testing to ensure interactions work as expected

### Review Checklist

- [ ] An editor can accept a submission for review
- [ ] An editor can reject a submission for review
- [ ] An editor can request a resubmission on a submission
- [ ] Reviewers can access the submission review page only when the submission is accepted for review

### Accessibility Checklist

- [ ] The controls for determining a submission's fitness for review are announceable via screen reader
- [ ] The text for the controls exists in the i18n.js file
- [ ] The language for the controls uses [plain language](https://sheribyrnehaber.com/plain-language-essential-for-content-accessibility/)

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/754?planning-poker) with ZenHub @gmeben @stephanievaskomsu @vilagshe @wreality

**Comment by Sruthin86** [comment]
**Work completed** 

- Added buttons for different stages of review

**Next steps**

- Configure confirmation modals for each button.
- Add mutations to update the backend.
- Cypress and Jest tests.

**Comment by vilagshe** [comment]
Work completed

- Added context menu with options for different stages of review
- Added modal popup to confirm status change
