### ISSUE TITLE
Submission Statuses

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#755]
### Problem/Why
Currently, there is no established way to set or view the status of a submission. This is important because reviews will rely on this heavily in order for those participating in the review to know where the submission is in its [workflow](https://miro.com/app/board/o9J_l654lxo=/). 

### Goal/What
Implement the backend infrastructure that allows the state of a submission to be designated under the following:

* Initially Submitted
* Awaiting Resubmission
* Resubmitted
* Awaiting Review
* Rejected
* Accepted as Final
* Expired
* Under Review
* Awaiting Decision
* Awaiting Revision
* Archived
* Deleted

### Solution/How
Write a migration to update submission table with a new column `status`.  Update the GraphQL schema to reflect the new `status` property of submissions using graphql Enums. Write a PHPUnit test to assert that a submission's status can be retrieved and changed via Eloquent.

### To Do / Acceptance Criteria

- [x] Write migration
- [x] Update `Submission` model
- [x] Update GraphQL schema
- [x] Add PHPUnit testing

### Review Checklist

- [ ] The status of a submission can be viewed via query from the GraphQL endpoint
- [ ] The status of a submission can be viewed via Eloquent (ex: `$submission->status`)
- [ ] The status of a submission can be changed via Eloquent
- [ ] All new and existing tests pass

**Comment by wreality** [comment]
We should make use of graphql enums here: 
https://lighthouse-php.com/master/the-basics/types.html#enum

**Comment by sattler9** [comment]
In a discussion, we have decided to not enable the statuses to be customizable due to FPR being opinionated and to save future complications.

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/755?planning-poker) with ZenHub @gmeben @Sruthin86 @wreality @amareshjoshi

**Comment by gmeben** [comment]
I've decided against using enum to represent the new column data for the reasons outlined in this article: https://komlenic.com/244/8-reasons-why-mysqls-enum-data-type-is-evil/

These reasons especially:

* Changing the member list of ENUM columns is very expensive.
* ENUM columns may only offer limited or negligible effects on optimization.
* ENUM can store up to 65,535 values. No, you shouldn't try it. More than 20 becomes unwieldy and certainly more than 50 is just insane to manage and work with.
