### ISSUE TITLE
Utility of document oriented database

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#77]
Previous Card: https://trello.com/c/ot6zelSo/48-determine-development-stack

---

**Problem/Why**

The development team isn't entirely sure where a document store might be useful to the project, but it seems worth investigating.

---

**Goal/What**

Produce research and some opinions to report to the team so that we can make a decision regarding the utility/benefit of adding a document store to the project.

---

**Solution/How
Added notes on research to the CCR architecture document:
https://docs.google.com/document/d/15qTFcvSox0ZxL1gI1V98RxRcqIT2sAob17i7amd-42I/edit#heading=h.i5ej7tig9g64
--- 
### To Do 

- [x] Research usage cases for document stores
- [x] Report that research out to the team for discussion

### Review Checklist 
 - [x] Presentation was helpful to the team and answered the needed questions.

> Trello Source: https://trello.com/c/fq0UNi6X

**Comment by sattler9** [comment]
Will report out at Monday, April 9th during team time

**Comment by amareshjoshi** [comment]
Added notes on research to the CCR architecture document:
(https://docs.google.com/document/d/15qTFcvSox0ZxL1gI1V98RxRcqIT2sAob17i7amd-42I/edit#heading=h.i5ej7tig9g64)
