### ISSUE TITLE
Notification Popup Default Message

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#783]
### Problem/Why
Currently, if a user that has no notifications clicks on the notification popup component, they will see a popup container with two buttons "View More" and "Dismiss All" and nothing else.

### Goal/What
Add a default "No Notifications" message to occupy the body of the notification popup component when a user has no notifications.

### Solution/How
Add a conditionally displayed element within the `notifications-container` wrapper to display a default "No Notifications" message if there are no notifications.

### To Do / Acceptance Criteria

- [x] Add the new conditionally displayed element to the notification popup template
- [x] Add an assertion to test that the default message appears

### Review Checklist

- [x] All new and existing tests pass
- [x] The default message is an i18n translated string

### Accessibility Checklist

- [x] There are no color contrast violations introduced
- [x] Text is announce-able by a screen reader
- [x] Text can be accessed using the keyboard only

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/783?planning-poker) with ZenHub @gmeben @Sruthin86 @wreality
