### ISSUE TITLE
User Roles and Permissions

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#79]
**Problem/Why**

For security reasons, not all users can have the same level of access to all resources and functionality within the system. The current system does not identify the roles and permissions of users and has no enforcement of what actions within the system that users are allowed to perform. 

---

**Goal/What**

Implement into CCR a framework of user roles and user permissions so that user behavior can be limited as specified out of concern for security.

1. User roles
2. User role management
3. User permissions
4. User permission management

---

**Solution/How**

https://trello.com/c/BAEsAQBu/61-develop-user-roles

https://trello.com/c/Np2eCHPM/62-develop-user-permissions

--- 
### To Do 
- [ ] https://trello.com/c/BAEsAQBu/61-develop-user-roles 
- [ ] https://trello.com/c/Np2eCHPM/62-develop-user-permissions 
## Attachments 
 
- [CCR Actions by Role](https://docs.google.com/spreadsheets/d/1j6TUtNlN_nM6TNpZtCOMCU8i7HJ8dVJCUI4RfcUkQuc/edit#gid=0) 
- [Is parent to Develop User Permissions](https://trello.com/c/Np2eCHPM/62-develop-user-permissions#sf-dependencies&dependencyType=is_parent_to&dependencyId=5ff5e440afbbd608d7d8a987&resolved=false) 
- [Is parent to Develop User Roles](https://trello.com/c/BAEsAQBu/61-develop-user-roles#sf-dependencies&dependencyType=is_parent_to&dependencyId=5ff5e35730df6d8ea82093a2&resolved=false) 
 
> Trello Source: https://trello.com/c/zqmBjbeb

**Comment by gmeben** [comment]
@wreality Shared a third-party package that looks like it should address the technical implementation of adding a roles and permissions system to CCR: https://spatie.be/docs/laravel-permission/v3/introduction

I'll be continuing to evaluate this package and update the related issues and their estimates as necessary.

**Comment by gmeben** [comment]
The current estimate for this issue still seems accurate `8` given that the amount of time subtracted from implementing the scaffolding necessary for roles and permissions is offset by the cost of learning the third-party tool, but the good news is that this will probably eliminate the need for the additional work for permissions here: https://app.zenhub.com/workspaces/ccr-5ff39ba363391e0019713c87/issues/mesh-research/ccr/81
