### ISSUE TITLE
Add database schema and GraphQL endpoints for user profile data

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#8]
**Problem/Why**

There is currently not a way for users to describe metadata about themselves into the applicaiton.

---

**Goal/What**

The user database should include profile data about users.  Reference the metadata collected in #64 for the types of information that should be collected.

---

**Solution/How**

The implementation in the database should be flexible so as to not require database migrations to add user metadata fields in the future, especially as these fields do not need to be queried / joined individually.  If there _are_ some fields that would be joined / filtered against, those should be added as columns directly.

---

### To Do / Acceptance Criteria

- [x] Create a new JSON column on the users table for storing user profile metadata
- [x] Add the user profile metadata field to the user type in the graphql schema
- [x] Add the user profile metadata field to the existing updateUser mutation
- [x] Implement tests to ensure the data can be queried and mutated.
- [x] Implement profile metadata validation (only accept known fields, and set reasonable max length limits)

### Review Checklist

- [x] Tests pass
- [x] User profile data is stored and associated with the user.
- [x] User profile fields are flexible.

**Comment by gmeben** [comment]
There's no built in JSON scalar type in GraphQL as far as I can tell. When defining the metadata column in the GraphQL schema as a `String` type, queries represent the stored JSON with escaped quotes in the result regardless of the stored JSON containing escaped quotes: 

```JSON
{
  "data": {
    "users": {
      "data": [
        {
          "id": "1",
          "profile_metadata": "{\"Phone\": \"444-111-9999\", \"Salutation\": \"mrs.\", \"Mailing Address\": {\"City\": \"Seattle\", \"State\": \"WA\", \"Postal Code\": \"98052\", \"Street Address\": \"20341 Whitworth Institute 405 N. Whitworth\"}}"
        }
      ]
    }
  }
}
```

If we want results to represent this field as a fully-parsed JSON object, like this...

```
{
  "data": {
    "users": {
      "data": [
        {
          "id": "1",
          "profile_metadata": {
            "Salutation": "mrs.",
            "Phone": "444-111-9999",
            "Mailing Address": {
              "City": "Seattle",
              "State": "WA",
              "Postal Code": "98052",
              "Street Address": "20341 Whitworth Institute 405 N. Whitworth"
            }
          }
        }
      ]
    }
  }
}
```

...then we'll likely need to implement this third party package: [graphql-type-json](https://github.com/taion/graphql-type-json)

However, if we're comfortable just parsing the result on the client, then we don't need to implement this.

@wreality @Sruthin86 Thoughts?

**Comment by wreality** [comment]
Look at this instead: https://github.com/mll-lab/graphql-php-scalars

I implemented it and then removed it in the testing stuff. It worked perfectly I just didn't end up needing it in the end. 

Lighthouse docs include a reference to it: https://lighthouse-php.com/5.3/the-basics/types.html#scalar

**Comment by wreality** [comment]
Actually we'd probably still want the package you referenced on the client. That way we get validation and serializing/deserializing on the scalar type on the client. 

Would probably help pick up errors quicker.

**Comment by gmeben** [comment]
For Spring Release, Brian and I found today that an acceptable strategy to proceed with is to keep the database field as a JSON type and use a statically-defined list of acceptable key names to represent profile metadata on the GraphQL schema and implement validation to check that provided values are strings with a reasonable max value length. 

At a later time, we'll implement the necessary functionality for enabling admins to build forms for submitting custom properties and values for their users' profile metadata.

**Comment by gmeben** [comment]
I updated the validation task and completed it.

**Comment by wreality** [comment]
Everything looks good as far as acceptance criteria.  PR #168 is open with some non-functional changes to be discussed addressed.
