### ISSUE TITLE
Implement User Roles in Database

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#80]
**Problem/Why**

There is no framework in place that defines user roles within CCR. There is a chance the current understanding of user roles in the attached spreadsheet may be outdated. As of now, the current understanding is that there is a role relative to the application as a whole (application administrator), roles relative to publications (publication administrator, editor), and roles relative to submissions (review coordinator, reviewer, submitter). These all have very different concerns with regard to functionality and security.

---

**Goal/What**

Double-check with team and stakeholders that the current understanding of roles is correct. Develop a framework to define user roles and associate them with users.

---

**Solution/How**

Just to be safe, consult with team and stakeholders (again) to verify that the currently defined roles are correct.

~Design a database schema for user roles. This will likely involve creating additional tables: a `user_roles_publications` table for roles relative to publications, and a `user_roles_submissions` for roles relative to submissions. Because these roles have a many-to-many relationship with publications, submissions, and users, it will be necessary to create linking tables between these tables and the existing table for users, publications, and submissions.~

~Application Administrator is currently the only role relative to the application with a one-to-one relationship with users. It may not be necessary to create a separate table for this role.~

Install the third-party package `spatie/laravel-permissions` to establish the scaffolding for user roles and permissions by role.

Create migrations to persist roles to the database.

Write tests to ensure functionality works.
--- 

### To Do 

- [x] Determine that an Application Administrator would be best suited as a "Super User" https://spatie.be/docs/laravel-permission/v3/basic-usage/super-admin
- [x] ~Hold short meeting to discuss currently defined user roles~ Discuss currently defined user roles via message
- [x] Write migrations for creating the necessary tables for user roles
- [x] Write migrations for populating the necessary data for user roles

## Attachments 
 
- [CCR Actions by Role](https://docs.google.com/spreadsheets/d/1j6TUtNlN_nM6TNpZtCOMCU8i7HJ8dVJCUI4RfcUkQuc/edit#gid=0) 
- [Is child to User Roles and Permissions](https://trello.com/c/zqmBjbeb/57-user-roles-and-permissions#sf-dependencies&dependencyType=is_child_to&dependencyId=5ff37c30cbbf5283bca485a2&resolved=false) 
 
> Trello Source: https://trello.com/c/BAEsAQBu

**Comment by gmeben** [comment]
@wreality Shared a third-party package that looks like it should address the technical implementation of adding a roles and permissions system to CCR: https://spatie.be/docs/laravel-permission/v3/introduction

I'll be continuing to evaluate this package and update the related issues and their estimates as necessary.

**Comment by gmeben** [comment]
Instead of a meeting, I decided to share with the team the current understanding of user roles via message: https://teams.microsoft.com/l/message/19:538e8356f84e48c686de71d62f09f1e5@thread.skype/1611589076054?tenantId=22177130-642f-41d9-9211-74237ad5687d&groupId=9ca8e1ea-de79-4fee-b2ac-ad876872ea81&parentMessageId=1611589076054&teamName=PPJ&channelName=General&createdTime=1611589076054

**Comment by gmeben** [comment]
Right now I've installed the third-party package and I created a new unit test `UserPermissionsTest` to ensure it works as expected, which I test with `lando artisan test --testsuite=Feature --filter=UserPermissionsTest` while in the `backend` directory.

I'm running into issues with data persisting in the database despite using the `RefreshDatabase` trait because I created a new test role without the use of a factory.

**Comment by gmeben** [comment]
The current estimate for this issue still seems accurate 8 given that the amount of time subtracted from implementing the scaffolding necessary for roles and permissions is offset by the cost of learning the third-party tool, but the good news is that this will probably eliminate the need for the additional work for permissions here: https://app.zenhub.com/workspaces/ccr-5ff39ba363391e0019713c87/issues/mesh-research/ccr/81

**Comment by gmeben** [comment]
While it's not clear if using the `Gate::before` and `Gate::after` AuthServiceProvider techniques are the _best_ for implementing the "super user" abilities of Application Administrators, they appear to be suitable techniques. If they are found to be unsuitable, then we can fallback to the typical role-based usage to enable permissions for Application Administrators.
