### ISSUE TITLE
Develop User Permissions

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#81]
**Problem/Why**

The current understanding of what actions are allowed (permissions) by role in the attached spreadsheet is not fully defined. Attempting to fully define them now (February 2020) is premature considering how early the application currently is in its development. There are currently no permissions formally represented in the system. It is not yet confirmed that permissions, when implemented through `spatie/laravel-permissions`, will query as expected from the GraphQL endpoint.

---

**Goal/What**

Define the first permission in the system via migration and write tests to ensure that it is queryable from the GraphQL endpoint.

---

**Solution/How**

- [x] Write a Laravel migration to add the first test `reset passwords of other users`
- [x] Write PHPUnit tests for the following:
    - [x] Check that his permission exists
    - [x] Check that the permission is returned on the GraphQL endpoint as expected for a user assigned with this permission
    - [x] Check that the permission is not returned on the GraphQL endpoint for a user not assigned with this permission

--- 

### Review Checklist 

- [x] The new permission exists in the `permissions` table
- [x] PHPUnit tests successfully run locally
 
## Attachments 
 
- [CCR Actions by Roles](https://docs.google.com/spreadsheets/d/1j6TUtNlN_nM6TNpZtCOMCU8i7HJ8dVJCUI4RfcUkQuc/edit#gid=0) 
- [Is child to User Roles and Permissions](https://trello.com/c/zqmBjbeb/57-user-roles-and-permissions#sf-dependencies&dependencyType=is_child_to&dependencyId=5ff37c30cbbf5283bca485a2&resolved=false) 
- [Is child to User Roles and Permissions](https://trello.com/c/zqmBjbeb/57-user-roles-and-permissions#sf-dependencies&dependencyType=is_child_to&dependencyId=5ff37c30cbbf5283bca485a2&resolved=false) 
 
> Trello Source: https://trello.com/c/Np2eCHPM

**Comment by gmeben** [comment]
I did a lot of research on StackOverflow today looking for questions that are similar to the current dilemma that occurred to me from while working on this card. This dilemma is the implementation of persistent database records from a third-party package's API (spatie/laravel-permission) for a Laravel app intended for replication, and here are the most relevant threads I found: 

- https://stackoverflow.com/questions/54927408/how-to-create-roles-and-permissions-in-laravel-permission-when-moving-to-new-env
- https://stackoverflow.com/questions/28679755/laravel-migrations-keep-them-forever-what-is-best-practice

**Comment by gmeben** [comment]
Relevant video, Implementing authorization in web applications and APIs - Dominick Baier & Brock Allen: https://www.youtube.com/watch?v=EJeZ3YNnqz8

**Comment by gmeben** [comment]
Here are my takeaways from that video.

**Good Authoriziation (Permission) Flow**

1. Client authenticates with identity provider to receive an identity token
2. Application consults with authorization provider to handle visible elements of the UI 
3. Any call to local APIs pass along the client identity
4. local APIs use the client identity to get specific permissions from the authorization provider and only get the data pertinent to the client identity

We should avoid overloading the security tokens with claims about roles and permission information. 

It's okay if we extend the GraphQL endpoint with that info, however.

**Comment by gmeben** [comment]
These are the relevant docs that helped me with this card:

* https://spatie.be/docs/laravel-permission/v3/basic-usage/basic-usage
* https://lighthouse-php.com/5.2/api-reference/directives.html#can

Extending the GraphQL schema for permissions was deceptively easy.
