### ISSUE TITLE
Add missing translation keys for PublicationsPage.vue

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#824]
### Problem/Why
A number of strings in PublicationsPage.vue are not wrapped in translation functions and so are not translatable in their current form.

### Goal/What
String content is stored in the translation index to enable translations.

### To Do / Acceptance Criteria
- [ ] Create keys in translation index for the various strings in the file
- [ ] Replace each string in PublicationsPage.vue with its corresponding translation method and key

### Review Checklist

- [ ] Tests pass
- [ ] Strings are translated.

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/824?planning-poker) with ZenHub @gmeben @Sruthin86 @wreality
