### ISSUE TITLE
Improve reliability of cypress when running under Github Actions

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#827]
### Problem/Why
Cypress tests when running under CI often crash.

### Goal/What
Cypress tests should setup and run as fast as is possible and not crash mid run.

### Solution/How
Running the cypress runner directly in the action instead of in a Lando container should reduce the resource needs in the github runner and result in fewer crashes.

### To Do / Acceptance Criteria

- [x] Rewrite workflow to 
  - [x] install composer and yarn deps directly
  - [x] spin up the app and serve on localhost using sqlite DB
  - [x] run the cypress github action against the localhost server.

### Review Checklist

- [x] Test run as usual

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/827?planning-poker) with ZenHub @gmeben @Sruthin86 @wreality
