### ISSUE TITLE
Extract makeNotify function into a composable

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#828]
### Problem/Why
A number of forms use a local "makeNotify" function that is largely identical in each case.

### Goal/What
Improve maintainability and DRY principles

### Solution/How
Extract the makeNotify function out into a new composable and rewrite each component that makes use of a local makeNotify function to use the composable.

### To Do / Acceptance Criteria

- [x] Create `src/use/guiElements` with a useFeedbackMessages function
- [x] Refactor `client/src/pages/SubmissionDetails.vue`
- [x] Refactor `client/src/pages/SubmissionPage.vue`
- [x] Refactor `client/src/pages/Admin/PublicationDetails.vue`
- [x] Refactor `client/src/pages/Admin/PublicationsPage.vue`
- [x] Refactor `client/src/pages/ProfilePage.vue`
- [x] Remove all //TODO comments related to this issue.

### Review Checklist

- [x] Unit tests pass
- [x] E2E tests pass

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/828?planning-poker) with ZenHub @gmeben @Sruthin86 @wreality
