### ISSUE TITLE
Investigate Tiptap WYSIWYG  editor.

### ISSUE THREAD

**Issue by Sruthin86** [MESH-Research/CCR#830]
### Problem/Why
We don't have a WYSIWYG editor for  editing submissions. 

### Goal/What
Investigate [Tiptap](https://tiptap.dev/api/editor/) and which is a rich text WYSIWYG editor to identify its potential and make a decision to use it in our stack.

### Solution/How
Build a working prototype to demonstrate the capabilities of Tiptop and decide and present it to the team.

### To Do / Acceptance Criteria
- [x] Build prototype.
- [x] Present the prototype to the team.
- [x] Determine how to add UI elements.
- [x] Evaluate the editor for a11y.
- [x] Evaluate Tiptip provides protection for HTML injection.

**Comment by sattler9** [comment]
There is no working example with Vue 3.

**Comment by Sruthin86** [comment]
**Work completed**

- Implemented a working example of tiptap editor.
- Added functionality to add headings.
- Added functionality to bold the text
- Added functionality to highlight text
- Added a character limit to the text (just like twitter)

**Next Steps**

- I can demo the functionality of a working example of tiptap with Vue3. I think we can use this going forward.

**Comment by wreality** [comment]
> * I can demo the functionality of a working example of tiptap with Vue3. I think we can use this going forward.

Sounds good @Sruthin86. Moved to Review/QA pipeline.
