### ISSUE TITLE
Add unit tests for the pagination composable

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#831]
### Problem/Why
There are no unit (jest) tests verifying the functionality of `src/use/pagination.js`

### Goal/What
Pagination.js is included in the test suite

### Solution/How
Write unit tests to confirm the functionality of pagination.js

### To Do / Acceptance Criteria

- [x] Write unit tests `src/usr/pagination.jest.spec.js`

### Review Checklist

- [x] Unit tests pass
- [x] Unit tests assert all functionality of the composable.

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/831?planning-poker) with ZenHub @gmeben @Sruthin86 @wreality
