### ISSUE TITLE
Wireframes for Submission Comment/Review

### ISSUE THREAD

**Issue by stephanievaskomsu** [MESH-Research/CCR#833]
### Problem/Why
There is no established view/feel of what the the submission viewing/editing page looks like. 

### Goal/What
Create wireframes for submission commenting and holistic review on the submission viewing/editing page.

### Solution/How
Develop a mockup/wireframe within Miro.

### To Do / Acceptance Criteria
- [x] Create low-fidelity wireframes for Monday Feb 5

### Review Checklist
- [x] Submission text content is represented within the wireframe
- [x] Holistic comments are represented within the wireframe
- [x] Inline comments are represented within the wireframe

### Accessibility Checklist
- [ ] The layout of the wireframe can be adapted to differently sized viewports

**Comment by sattler9** [comment]
Feedback from PPJ on Oct. 4th, 2021 at the editorial / CCR meeting on this [miro board](https://miro.com/app/board/o9J_ltyWt-w=/)

Kurt likes using different versions for the reader’s report (ver F + B) and PHC  - “for reader report comments (private), i'd vote for variation F (on the review page) but with the comments in the sidebar so folks can read the submission and any in-line comments as they compose those summary comments; for holistic comments (public), it might be interesting/useful to put them on the submission details so you have a mechanism to get folks back into the system”

Shelby likes A or C for PHC

Chris seems to like A or A-1 or C. Also wants the PHC tightly linked but separate.

Whispers more for the reader’s report to speak to the editor.

Sidebar is good for the reader’s report - general agreement by PPJ Ed team

May want to refer to section of the article as they make comments

**Comment by gmeben** [comment]
I seem to have moved this into the Icebox column by accident yesterday. 

I'm going to move this into the In Progress column and assign @stephanievaskomsu since she's already worked on this. If a velocity needs to be associated with this issue, one can be added that includes the effort expended during a typical workday (like we previously discussed as a team on in our review/retrospective meeting on Tuesday).
