### ISSUE TITLE
Mock Review Submission View with Mocked Data

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#834]
### Problem/Why
Currently, there's no layout(s) of a page to view a submission's contents within CCR for a user to interact with. 

### Goal/What
Have a simple interface in CCR created with mocked text-based content to represent how a manuscript would appear within CCR to those participating in its review process. This should implement the design from the wireframes created in Issue #833. This view should be accessible from the Submission Details page.

### Solution/How
Design within the browser a prototype page using Quasar components following the design of the wireframes. The text should be static and mocked (lorem ipsum or equivalent). There should be elements to represent the content generated from interactions like holistic and inline commenting. 

### To Do / Acceptance Criteria

- [x] Add hyperlink to the Submission Details page
- [x] Design a page according to the wireframes from #833
- [x] Add a Cypress test asserting that this page can be navigated to via links after login

### Review Checklist

- [x] Submission text is represented
- [x] Holistic comments are represented
- [x] Inline comments are represented

### Accessibility Checklist

- [x] The submission text adapts to changing viewports in a way that remains readable
- [x] There are no color contrast issues introduced
- [x] Submission text is detectable by a screen reader
- [x] Holistic comment text is detectable by a screen reader
- [x] Inline comment text is detectable by a screen reader
- [x] Inline comments can be accessed via keyboard interactions exclusively

**Comment by wreality** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/834?planning-poker) with ZenHub @gmeben @Sruthin86 @sattler9

**Comment by wreality** [comment]
@gmben @Sruthin86  @sattler  It looks to me that @gmeben 's issue here is well defined.  I opened the poker figuring we could add our votes if time permits. (Feel free to not vote if it needs more discussion at team time)

**Comment by gmeben** [comment]
I want to capture the annotation systems we shared earlier:

1. https://via.hypothes.is/https://educatorinnovator.org/wp-content/uploads/2019/10/EJ1084Mar19Miles.pdf
2. https://www.frankenbook.org/pub/1hqhta90/release/1
3. https://cuny.manifoldapp.org/read/bb95893e-3b92-4dce-b0d1-35293baecd9e/section/807eedb7-3200-432e-b2b6-30b2b35b5221

**Comment by gmeben** [comment]
Quasar dev describes how to implement resizing on a QDrawer: https://github.com/quasarframework/quasar/issues/7099#issuecomment-633395879

**Comment by Sruthin86** [comment]
Feedback from review:

- Mockup the interface showing the comments with replies.

**Comment by gmeben** [comment]
![Screen Shot 2022-02-18 at 2.39.11 PM.png](https://images.zenhubusercontent.com/5ff7670b9384a948b4663b2d/22e6adf2-972d-4d6a-8924-43dde579bd62)

@stephanievaskomsu Here's the screenshot I took earlier. Feel free to annotate.

**Comment by gmeben** [comment]
![Screen Shot 2022-02-21 at 7.31.48 AM.png](https://images.zenhubusercontent.com/5ff7670b9384a948b4663b2d/59d8ba24-0523-47a0-9825-f698f4f7d1ce)

![Screen Shot 2022-02-21 at 7.32.28 AM.png](https://images.zenhubusercontent.com/5ff7670b9384a948b4663b2d/85504be5-65cb-4bdb-8c05-308d2410bb23)

@stephanievaskomsu Here are screenshots with comment replies added.

**Comment by Sruthin86** [comment]
Feedback from review:

- The indentation for replies on the comments can be a setting and perhaps we can have some A/B testing done with and without the indentation.

**Comment by sattler9** [comment]
Lots of comments from the review. Grant will write up a new ticket to complete the work and make the code more "containerized"

**Comment by gmeben** [comment]
Earlier today, we agreed that the additional improvements and refactoring that have been requested as part of the review will be addressed in a follow-up issue as all the original work outlined in the scope of this issue has been completed. That issue is #915.

All text is screen reader accessible (ChromeVox) via keyboard commands (ChromeVox modifier key + up arrow / ChromeVox modifier key + down arrow). I'm noting there's a need to improve the order of the text read on comments, however. I'll consider this as part of the work to be done in Issue #915 and will complete it there.
