### ISSUE TITLE
useDirty guard doesn't work when clicking logout

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#840]
### Problem/Why
If the user clicks logout while in a form that uses the dirtyguard composable (account profile, metadata) the dialog appears, but the user it logged out before they have an opportunity to choose a response.

### Goal/What
The logout navigation should wait until the dirtyguard has confirmed the user wants to exit the form.

### Solution/How
The logout button doesn't use the router, but instead calls the logout mutation directly.  The dirtyGuard composable users the onRouteBeforeLeave callback, which only is called on a new navigation requested of the router.  The logout link should link to a new page "Logout" that actually process the logout and redirects the user to the home page of the application.

### To Do / Acceptance Criteria

- [x] Create Logout.vue which onMounted triggers the logout actions that are currently called by the logout link
- [x] Update Logout link in header to trigger a router.push to the new logout page.
- [x] Update header cypress test to validate functionality

### Review Checklist

- [x] New tests are complete and passing
- [x] Existing jest tests pass
- [x] Existing cypress tests pass

### Accessibility Checklist
No accessibility issues wrt to this change.

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/840?planning-poker) with ZenHub @gmeben @Sruthin86 @wreality

**Comment by wreality** [comment]
Removed the unit test changes (there's just not much to test here) and instead added cypress test to validate the actual issue.
