### ISSUE TITLE
Add Publication’s Style Criteria to API

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#847]
### Problem/Why
There are no API fields to store / update a publications style criteria

### Goal/What
The api should have fields for storing style criteria for each publication. Each publication can have multiple values and each value has a name (short) and description. 

### Solution/How
A new type and field in create and update publication types for the StyleCriteria

### To Do / Acceptance Criteria

- [x] Create a new migration to create publication_style_criteria
- [x] Associate a belongs to relationship for style_criteria to publications
- [x] Create a new graphql type StyleCriteria with name and description fields
- [x] Add the StyleCriteria type to a style_criteria field in publication type
- [x] Create new StyleCriteria Input type
- [x] Update updatePublication to support updating Style Criteria
- [x] Add validation classes to ensure data integrity. 
- [x] Add unit tests to ensure retrievability and updatability of core values with appropriate validation criteria. 

### Review Checklist

- [x] unit tests pass
- [x] unit tests adequately test functionality described above. 

### Accessibility Checklist
Backend only, no accessibility concerns.

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/847?planning-poker) with ZenHub @gmeben @Sruthin86 @wreality
