### ISSUE TITLE
Create a Wireframe for the Drafting of Holistic Comments

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#848]
### Problem/Why
The wireframes that have been created for holistic comments do not show what the interface might look like when a user is drafting a holistic comment. 

### Goal/What
Wireframe how a component would appear for someone drafting a holistic comment. It should support all specified features. 

### Solution/How
Create a wireframe in Miro or Adobe XD. When finished, meet with the team to share, review, and record findings.

### To Do / Acceptance Criteria

- [x] Create wireframe
- [x] Obtain and incorporate feedback from the CCR team
- [x] Check with PPJ for their feedback on the mockups

### Review Checklist

- [x] The wireframe supports all specified features
- [x] Agreement within the CCR team that the wireframe is at a state to be developed within the system

### Accessibility Checklist

- [ ] The design can plausibly adapt to viewports of different sizes

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/848?planning-poker) with ZenHub @gmeben @Sruthin86 @wreality

**Comment by sattler9** [comment]
I didn't invite Stephanie, who has actually started working on this, to the planning poker because she wasn't in the meeting at the time we reviewed this.

**Comment by sattler9** [comment]
Question about 1 ticket per round of feedback vs. going around and around and estimating this ticket to include all the rounds of feedback and tweaking. For this ticket, the estimate will be inclusive of all the rounds of feedback until the CCR team has reached a conclusion that enables the developers to proceed in creating the platform.

**Comment by gmeben** [comment]
I originally included "The wireframe supports all specified features" as a review checklist items under the impression that we would define those desired features before working on this issue.

The currently known features are loosely:

- An editable text area to draft a holistic comment
- A button to submit the drafted text and post a holistic comment
- Automatic saving of drafts
- An indicator for when a draft is automatically saved

**Comment by sattler9** [comment]
Grant is documenting extra questions that we'll ask PPJ to comment on asynchronously in this [google doc](https://docs.google.com/document/d/1SS2PL2-QgmRGAD5KVNdLOYNbYiZhLrNWlp8Kit_pcaQ/edit)
