### ISSUE TITLE
Basic User Access - Registration

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#86]
**Problem/Why**

There is no way for a user to be created within the system. 

---

**Goal/What**

Create a system for users to sign up and register themselves as a user in the system. The user should be given options to sign up using custom credentials (email, password) or by authorizing an external provider (Google, Twitter, etc.) to authenticate.

Upon registering, the system should check and notify the user if the user has multiple accounts (Email, Google, Twitter).

---

**Solution/How**

Utilize the existing view for a sign up form. Write front-end code to handle sending a POST request to the back-end. Add a route for handling the POST request. Write back-end code for processing the POST request.

--- 
## Attachments 
 
- [Is parent to Internal user creation](https://trello.com/c/M3LP21fR/55-internal-user-creation#sf-dependencies&dependencyType=is_parent_to&dependencyId=5ff3636d7a0a5a160a755f20&resolved=false) 
- [Is parent to Verify user email addresses](https://trello.com/c/gXhHTMUg/56-verify-user-email-addresses#sf-dependencies&dependencyType=is_parent_to&dependencyId=5ff3651d9c416c51b35a9ed0&resolved=false) 
- [Is parent to User registration from external source](https://trello.com/c/GVTKSYxd/63-user-registration-from-external-source#sf-dependencies&dependencyType=is_parent_to&dependencyId=5ff5f33a4169a612c245b907&resolved=false) 
 
> Trello Source: https://trello.com/c/99N2A9ZC

**Comment by sattler9** [comment]
external sources pushed to later release
