### ISSUE TITLE
Verify user email addresses

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#87]
**Problem/Why**

Email addresses are currently not verified.

---

**Goal/What**

Emails should be verified whenever an email is updated or added to the application.  

---

**Solution/How**

Send the user an email at the new address with a link to click to verify the email.  The email verification should be recorded in the persistence layer.  

--- 
### To Do 
- [x] Write backend functionality to send an email upon the email address changing
- [x] Extend GraphQL schema to accept verification token and update `email_verified_at` upon valid token receipt.
- [x] Add frontend route to receive verification clicks
- [x] Write frontend page to connect to GraphQL endpoint for email verification
- [x] Extend frontend to provide user feedback on the success or failure of email verification.
- [x] Write unit/integration testing as appropriate 

### Review Checklist 
- [x] An email should be sent when an email address is updated. 
- [x] The link in the email should update the verification record 
- [x] The link should only be valid for the email address it was sent to. (If a user changes the email a second time, a verification link sent to another account shouldn't be able to verify the current email.)
- [x] The verification method should be secure and not allow verification of emails that the user does not control. (I.e. the token that will be required is not guessable) 

 
## Attachments 
 
- [Is blocked by Internal user creation](https://trello.com/c/M3LP21fR/55-internal-user-creation#sf-dependencies&dependencyType=is_blocked_by&dependencyId=5ff3636d7a0a5a160a755f20&resolved=false) 
- [Is child to System User Registration](https://trello.com/c/99N2A9ZC/15-system-user-registration#sf-dependencies&dependencyType=is_child_to&dependencyId=5f6a0648f52b64894091a375&resolved=false) 
 
> Trello Source: https://trello.com/c/gXhHTMUg

**Comment by sattler9** [comment]
We dropped this to a 5 from an 8 because the bigger effort was the Lando setup done in a different ticket/issue.
