### ISSUE TITLE
Implement userCreate API endpoints

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#90]
**Problem/Why**

It is not possible to create a new user using the API

---

**Goal/What**

An API user can create a new user.  Data should be validated and persisted in the database.  Any errors should be descriptively sent to the user.

---

**Solution/How**

Create a `userCreate` GraphQL endpoint that accepts new user data.  The endpoint should return the created users.  

**See parent ticket #60 for schema and validation criteria.**

---
### To Do / Acceptance Criteria
- [x] A userCreate endpoint exists
- [x] Improper data is rejected and sensible error message are returned
### Review Checklist
- [x] Able to create a new user via the api.

**Comment by wreality** [comment]
If name is not provided in the request, an SQL error occurs b/c name does not have a default value.

**Comment by Sruthin86** [comment]
The developers worked together on the implementing the GraphQL schema for user creation. Code is checked in and a pull request created. 
MESH-Research/CCR: Pull Request 94
