### ISSUE TITLE
Define API spec for reviewing. 

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#910]
### Problem/Why
The structure of the API Queries and mutations for review of a submission need to be defined so that work can continue on the API and client implementation concurrently. 

### Goal/What
Define the API spec for GraphQL fields related to reviewing functionality 

### Solution/How
In the body of this ticket, document the intended API surface for reviewing a submission using SDL. implementation details such as validation requirements are out of scope. 

### To Do / Acceptance Criteria

- [x] API provides
  - [x] Ability to create a new inline comment 
  - [x] Ability to create a new reply to an inline comment 
  - [x] ability to create a new overall comment 
  - [x] ability to create a new overall comment reply
  - [x] retrieval of a submission’s inline and overall comments
  - [x] New types that describe the objects available.
    - [x] Style Criteria associated with an inline comment

### Review Checklist

- [ ] API spec describes/meets needs of review functionality. 

### Schema Spec in Graphql SDL
```
extend type Query {
  submission(id: ID!): Submission!
}
extend type Mutation {
   addInlineComment(submission_id: ID!, content: String!, style_criteria: [ID!]): InlineComment
   addInlineCommentReply(submission_id: ID!, content: String!, reply_to: ID!): InlineComment
   addOverallComment(submission_id: ID!, content: String!): OverallComment
   addOverallCommentReply(submission_id: ID!, content: String!, reply_to: ID!): OverallComment
}

type Submission {
   #existing fields
    id: ID!
    title: String
    created_at: DateTime!
    updated_at: DateTime
    publication: Publication!
    #PROPOSED UPDATE
    reviewers: [User!]!
    review_coordinators: [User!]!
    submitters: [User!]!
    files: [SubmissionFile]! 
    status: SubmissionStatus!
   #new fields
   inline_comments: [InlineComment!]!
   overall_comments: [OverallComment!]!
   content: SubmissionContent #This field is optional bc it may be null if the pandoc process is still importing the document
}

#Propose implementing as a type so content updates (i.e. new comments) don't force the update of the modified field on submissions)
type SubmissionContent {
  content: String!
  created_at: DateTime!
  modified_at: DateTime!
  src_file: SubmissionFile!
}

type InlineComment {
  id: ID!
  content: String!
  created_by: User!
  reply_to: InlineComment  #This references the particular message being replied to.
  parent: InlineComment #The top level comment this comment is under.
  created_at: DateTime!
  style_criteria: [String!] #Note, style criteria are saved as strings rather than a reference to the model to avoid issues with future changes to criteria names
}

type OverallComment {
  id: ID!
  content: String!
  created_by: User!
  reply_to: OverallComment
  parent: OverallComment
  created_at: DateTime!
}
```

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/910?planning-poker) with ZenHub @gmeben @Sruthin86 @wreality

**Comment by sattler9** [comment]
No frontend or backend work.

**Comment by gmeben** [comment]
As part of the review, I approve the spec as it's defined
