### ISSUE TITLE
Optimize Componentization of Mocked Submission Review

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#915]
### Problem/Why
The interface that was mocked up to demonstrate how a manuscript would appear within CCR to those participating in its review process was marked up in a way that is not reusable. Some of the components that have already been created were not named ideally either. There has also been more feedback provided from subsequent meetings regarding changes to the interface that have not yet been implemented or explored. 

### Goal/What
Create components that are named intuitively and address feedback provided up to now (March 2nd, 2022).

### Solution/How
Address all of the feedback that Brian left on pull request #907. 

Address all of the feedback from subsequent meetings outlined below. 

https://github.com/MESH-Research/CCR/pull/907/files

Make sure that all necessary components are created out of the markup and named accordingly. 

### To Do / Acceptance Criteria

- [x] Address all PR feedback, including componentization 
- [x] Add comment numbers to comments 
- [x] Add links in comment replies to the comments they're replying to 
- [x] ~~Add a list of users who have commented~~ 
- [x] Add control to toggle highlighting 
- [x] Add control to toggle dark mode
- [x] Explore different orders of comment replies 
- [x] Explore controls for increasing and decreasing font size of submission text
- [x] Re-order appearance of elements in comments to improve screen reading comprehension 
- [x] Add button for collapsing an inline comment thread
- [x] Add controls for changing the font a manuscript is presented in

### Review Checklist

- [x] All feedback comments in the pull request have been addressed
- [x] All additional feedback items outlined above have been addressed

### Accessibility Checklist

- [x] Screen reader reading is intuitive, understandable, and not difficult to navigate

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/915?planning-poker) with ZenHub @gmeben @Sruthin86 @wreality

**Comment by sattler9** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/915?planning-poker) with ZenHub @stephanievaskomsu

**Comment by gmeben** [comment]
I just wanted to capture that we changed the velocity earlier today from `3` to `5` because we added work that increases the scope of this issue that was not originally conceived when the issue was created.

My currently listed vote in Planning Poker is an accident. I agree with everyone else's `5` as the chosen velocity.

**Comment by gmeben** [comment]
Kurt made a good feature suggestion in today's meeting: Controls for filtering inline comments by style criteria

**Comment by gmeben** [comment]
It occurs to me that exploring different orders of comment replies would be better served by having legitimate test data to work with. As it stands, the data is duplicated between each comment, so the advantages and disadvantages of different types of sorted orders can't really be observed. 

For that reason, I'm going to consider the "Explore different orders of comment replies" task as finished for now but it will need to be revisited again.

**Comment by Sruthin86** [comment]
**Feedback from standup**

- A subtile slide down/up for the show/hide reply button
- Possibly make the controls a sticky (zoom, dark mode etc) or making it a flyout menu or a combination.
- A "show more" button for the comments if we decide to only show n number of lines.
- Should we hide action buttons (reply, hide replies, ...) unless there is focus on the comment? Look at Google docs for an example. 
- any icon that appears better than the high highlight.

**Comment by gmeben** [comment]
During today's meeting, we determined that there are considerations that discourage proceeding the implementation of the "list of commenters" section on the submission review page. Those considerations are the following:

* This element may crowd the inline comments drawer
* This element may be able to be represented elsewhere on the page, potentially as a dropdown from a button in the toolbar
* The purpose of this element may be able to be satisfied elsewhere on the site, such as markers beside the lists of users on the submission details page 

For these reasons, I'm revoking the task for "Add a list of users who have commented"
