### ISSUE TITLE
Create InlineCommentEditor component

### ISSUE THREAD

**Issue by Sruthin86** [MESH-Research/CCR#919]
### Problem/Why
There is no interface to add a new comment on the review page.

### Goal/What
Develop an interface that displays the Tiptap editor. This interface should allow the user to bold, italicize, make an ordered/unordered list, and add the ability to link text.

### Solution/How
Wireframe: https://miro.com/app/board/o9J_ltyWt-w=/?moveToWidget=3458764518536074124&cot=14

* Install the tiptap editor (https://tiptap.dev/installation/vue3), create a `CommentEditorContent` component.
* Create a `CommentEditor` Component using the above wireframe as a guide.

### To Do / Acceptance Criteria

- [x] Add an interface with text area to add a comment
- [x] Option to bold text is available 
- [x] Option to italicize text is available 
- [x] Option to make text into ordered/unordered list is available 
- [x] Option to link text  is available 
- [ ] ~~Cypress tests are written for the new interface~~

### Review Checklist

- [x] An interface exists with options to bold, italicize, make ordered/unordered list, and link text
- [x] All the aforementioned items buttons work in the interface.

### Accessibility Checklist

- [ ] ~~Cypress a11y tests pass without any issues.~~

**Comment by gmeben** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/919?planning-poker) with ZenHub @sattler9 @stephanievaskomsu @wreality @Sruthin86

**Comment by Sruthin86** [comment]
Work completed 

- Installed all the dependencies for tiptap
- Started working on the template  for inline comment editor

**Comment by gmeben** [comment]
Sruthin and I agreed that the Cypress test for this issue was unnecessary as it's an early-prototype of a mocked interface that's prone to being changed at any time. Therefore, the work that would be done developing the Cypress test would likely be wasted.
