### ISSUE TITLE
Create wireframe for draft view of inline comments

### ISSUE THREAD

**Issue by Sruthin86** [MESH-Research/CCR#921]
### Problem/Why
Currently there is no wireframe for a draft view of the of the inline comments section. 

### Goal/What
A wireframe showing the basic functions of drafting an inline comment is created and discussed with the team. 

### Solution/How
Use Miro to create wireframe for the draft view of inline comment section. 

### To Do / Acceptance Criteria

- [x] Wireframes are created using Miro
- [x] Team discusses and  agrees on the wireframe. 
- [x] Review with PPJ to have them answer questions

### Review Checklist

- [x] Wireframe of the draft view for inline comments is created.

**Comment by gmeben** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/921?planning-poker) with ZenHub @sattler9 @Sruthin86 @stephanievaskomsu @wreality

**Comment by gmeben** [comment]
@Sruthin86 I see that you were the one to add the `needs-refinement` label to this issue. If you feel the removal of this was mistaken, feel free to adjust this issue as necessary.
