### ISSUE TITLE
Inline comment reply interaction

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#978]
### Problem/Why
Clicking reply on a comment doesn't do anything ;-)

### Goal/What
Clicking reply should insert the InlineCommentEditor component at the contextually appropriate location below the chain of replies associated with the reply.

### Solution/How
Update SubmissionComment component to display the InlineCommentEditor when the reply button is clicked.

### To Do / Acceptance Criteria

- [x] Display CommentEditor when Reply is clicked
- [x] Add jest tests for SubmissionComment to verify functionality

### Review Checklist

- [ ] Comment editor appears in the appropriate location

### Accessibility Checklist

- [ ] ARIA/A11Y changes may be needed to contextualize the component.

**Comment by gmeben** [comment]
I'm removing "Close comment editor when close is clicked" as part of the acceptance criteria on this issue because that's more related to the scope of Issue #780

**Comment by wreality** [comment]
> related to the scope of Issue #780

Are you sure that's the right issue number ?

**Comment by gmeben** [comment]
@wreality Good catch. That was a typo. I meant #980.
